/** English (en-US) — marketAgent module strings(MarketingAgent,PRD §11) */
const enUS = {
  // Redirect shell(routes/market/agent.tsx)
  "shell.entering": "Entering MarketingAgent…",
  "shell.initFailed": "Failed to initialize MarketingAgent workspace",

  // Dock(market-agent-dock.tsx)
  "dock.open": "Open MarketingAgent",
  "dock.title": "MarketingAgent — marketing orchestration",
  "dock.contextCurrent": "Context: {{summary}}",
  "dock.defaultDesc": "Marketing orchestration hub · 7 specialist agents",
  "dock.preparing": "Preparing MarketingAgent workspace…",
  "dock.loadFailed": "Load failed: {{error}}",

  // Fleet badge(market-agent-fleet-badge.tsx)
  "fleet.ariaLabel": "MarketingAgent fleet status",
  "fleet.title": "MarketingAgent fleet · {{count}} agents",
  "fleet.dotTitle": "{{name}} · {{status}}",
  "fleet.lastAction": "Last: {{action}}",
  "fleet.summary.thinking": "{{count}} thinking",
  "fleet.summary.online": "{{active}}/{{total}} online",
  "fleet.summary.ready": "Fleet ready",
  "fleet.status.idle": "Idle",
  "fleet.status.online": "Online",
  "fleet.status.thinking": "Thinking",
  "fleet.status.tool": "Tool call",
  "fleet.dev.simulateTitle":
    "Emit market_agent_status via event-bus to verify monitoring-ws → store → UI chain",
  "fleet.dev.demo": "Demo",
  "fleet.dev.reset": "Reset",
  "fleet.agent.mkt-radar-agent.name": "Radar",
  "fleet.agent.mkt-radar-agent.role": "Signals, events & emerging trends",
  "fleet.agent.mkt-visibility-agent.name": "Visibility",
  "fleet.agent.mkt-visibility-agent.role": "GEO citation & SERP rankings",
  "fleet.agent.mkt-competitor-agent.name": "Competitor",
  "fleet.agent.mkt-competitor-agent.role": "Profiles & content strategy",
  "fleet.agent.mkt-trend-agent.name": "Trend",
  "fleet.agent.mkt-trend-agent.role": "Industry trends & forecasts",
  "fleet.agent.mkt-opportunity-agent.name": "Opportunity",
  "fleet.agent.mkt-opportunity-agent.role": "Demand evaluation & pipeline",
  "fleet.agent.mkt-action-agent.name": "Action",
  "fleet.agent.mkt-action-agent.role": "GTM action drafts & outreach",
  "fleet.agent.mkt-report-agent.name": "Reporter",
  "fleet.agent.mkt-report-agent.role": "Briefings, reports & summaries",

  "chips.srLabel": "Ask MarketingAgent",

  // ChatView(market-agent-chat-view.tsx)
  "chat.orchLabel": "Orchestration",
  "chat.inputPlaceholder": "Command MarketingAgent…",

  // E2 panel(market-agent-orchestration-panel.tsx)
  "panel.nodes.title": "Task nodes",
  "panel.nodes.empty": "No running tasks",
  "panel.nodes.running": "Running",
  "panel.context.title": "Market context",
  "panel.context.range": "Range: last {{count}} days",
  "panel.context.allProducts": "Product: all",
  "panel.context.product": "Product: {{id}}…",
  "panel.llm.title": "Model",
  "panel.llm.gatewayNote":
    "Chat model runs via the platform gateway (llm-pricing catalog, user credits) — no local LLM setup. Pipelines (briefs/profiles/GEO) run on the market module's own engine.",

  // Artifact card(market-agent-message-renderer.tsx)
  "artifact.kind.signal": "Signal",
  "artifact.kind.event": "Event",
  "artifact.kind.brief": "Brief",
  "artifact.kind.insight": "Insight",
  "artifact.kind.action": "Action",
  "artifact.kind.report": "Report",
  "artifact.kind.profile": "Profile",
  "artifact.kind.opportunity": "Opportunity",
  "artifact.kind.product": "Product",
  "artifact.kind.other": "Artifact",
  "artifact.producedBy": "By {{name}}",
  "artifact.needsReview": "needs review",

  // Empty state(market-agent-empty-state.tsx)
  "empty.subtitle":
    "Your AI marketing partner — state a goal; it decomposes, routes the fleet, calls module tools, and delivers",
  "empty.briefing.title": "Morning Brief · {{date}}",
  "empty.briefing.modelTag": "Generated by",
  "empty.briefing.generate": "Generate today's brief",
  "empty.briefing.generating": "Generating…",
  "empty.snapshot.loading": "Loading market snapshot…",
  "empty.snapshot.title": "Market snapshot (last 7 days)",
  "empty.snapshot.pending": "Pending signals",
  "empty.snapshot.events": "New events",
  "empty.snapshot.briefs": "Briefs",
  "empty.snapshot.highConf": "High-confidence",
  "empty.snapshot.sources": "{{total}} sources · {{errored}} errored",
  "empty.snapshot.unavailable":
    "Market snapshot unavailable{{error}} — ask directly; the agent pulls live data via tools",
  "empty.quick.geo.label": "Citation check",
  "empty.quick.geo.hint": "GEO citations & gaps",
  "empty.quick.geo.prompt":
    "How is Yinghuo's citation rate in AI answers? Which keywords are not cited, and where is the gap?",
  "empty.quick.signals.label": "Competitor moves",
  "empty.quick.signals.prompt":
    "What high-confidence competitor actions happened in the last 7 days? Give me the event list and highlights.",
  "empty.quick.signals.hint": "Signals & events",
  "empty.quick.competitor.label": "Competitor teardown",
  "empty.quick.competitor.prompt":
    "Analyze Label Studio's recent content strategy and its share of voice in our category.",
  "empty.quick.competitor.hint": "Profile & content",
  "empty.quick.opportunities.label": "Opportunities",
  "empty.quick.opportunities.prompt":
    "What opportunities need follow-up? Suggest next steps by intent and stage.",
  "empty.quick.opportunities.hint": "Pipeline & next steps",
  "empty.quick.actions.label": "Action funnel",
  "empty.quick.actions.prompt":
    "What's the state of the channel action funnel? Which ideas are stalled? Suggest next steps.",
  "empty.quick.actions.hint": "Outreach & execution",
  "empty.quick.briefing.label": "Morning brief",
  "empty.quick.briefing.prompt":
    "Give me a market morning brief: new signals, high-confidence events, citation changes, due actions and next-best-actions.",
  "empty.quick.briefing.hint": "Alignment & reporting",
};

export default enUS;
