#!/usr/bin/env python3
"""生成 50+ 合规检查清单模板 JSON 文件

写入 nn-market-resources/data/agents/normnomos.com/compliance-team/templates/
"""

import json
import os
from pathlib import Path

OUTPUT_DIR = Path(__file__).resolve().parents[4] / "nn-market-resources" / "data" / "agents" / "normnomos.com" / "compliance-team" / "templates"

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

TEMPLATES = [
    # =====================================================================
    # KYC / 开户合规 (8 templates)
    # =====================================================================
    {
        "slug": "kyc-onboarding-basic",
        "name": "KYC 基础开户合规检查",
        "category": "KYC开户合规",
        "description": "适用于所有客户的基础 KYC 开户核查流程，覆盖身份核验、制裁筛查与风险评估",
        "applicable_scenarios": ["银行开户", "证券开户", "支付机构"],
        "items": [
            {"task": "客户身份核验（护照/营业执照等有效证件）", "category": "身份核验", "guidance": "FATF Recommendation 10; 中国人民银行令〔2016〕第3号"},
            {"task": "制裁名单筛查（OFAC SDN / UN / EU / 中国公安部）", "category": "制裁筛查", "guidance": "OFAC 31 CFR Part 501; 联合国安理会决议"},
            {"task": "受益所有人识别（≥25% 股权/控制权）", "category": "UBO识别", "guidance": "FATF Recommendation 24; 中国人民银行令〔2018〕第2号"},
            {"task": "PEP 政治人物筛查", "category": "风险筛查", "guidance": "FATF Recommendation 12"},
            {"task": "负面新闻扫描", "category": "风险筛查", "guidance": "FATF Recommendation 10; Wolfsberg Group"},
            {"task": "风险评级（低/中/高）", "category": "风险评估", "guidance": "FATF Risk-Based Approach Guidance"},
            {"task": "客户尽职调查文件归档", "category": "文档归档", "guidance": "FATF Recommendation 11"},
            {"task": "合规审批", "category": "审批", "guidance": "内部合规政策"},
        ],
    },
    {
        "slug": "kyc-onboarding-enhanced",
        "name": "KYC 加强尽职调查（EDD）检查清单",
        "category": "KYC开户合规",
        "description": "针对高风险客户（高风险国家、PEP、复杂结构）的加强尽职调查",
        "applicable_scenarios": ["高风险国家客户", "PEP客户", "离岸公司"],
        "items": [
            {"task": "确认客户所在国家风险等级", "category": "风险评估", "guidance": "FATF High-Risk Jurisdictions List; EU AML List"},
            {"task": "获取高级管理层批准", "category": "审批", "guidance": "FATF Recommendation 10"},
            {"task": "深入识别资金来源与财富来源", "category": "资金来源", "guidance": "FATF Recommendation 10"},
            {"task": "审查客户商业背景与关联方", "category": "背景审查", "guidance": "FATF Recommendation 22"},
            {"task": "受益所有人层级穿透核查（直至自然人）", "category": "UBO识别", "guidance": "FATF Recommendation 24"},
            {"task": "获取额外身份证明文件", "category": "身份核验", "guidance": "FATF Recommendation 10"},
            {"task": "持续监控频率提升至季度/月度", "category": "持续监控", "guidance": "FATF Recommendation 20"},
            {"task": "年度复审确认客户信息更新", "category": "复审", "guidance": "内部合规政策"},
        ],
    },
    {
        "slug": "kyc-corporate-entity",
        "name": "企业客户 KYC 检查清单",
        "category": "KYC开户合规",
        "description": "企业客户开户时的公司文件核验、控制权结构识别与实控人穿透",
        "applicable_scenarios": ["公司开户", "合伙企业", "信托"],
        "items": [
            {"task": "核验营业执照/注册证书（含翻译件）", "category": "身份核验", "guidance": "中国人民银行令〔2016〕第3号 第10条"},
            {"task": "核对公司章程/合伙协议", "category": "身份核验"},
            {"task": "识别董事/高管名单及身份", "category": "UBO识别"},
            {"task": "绘制股权结构图（识别≥25%实控人）", "category": "UBO识别", "guidance": "FATF Recommendation 24"},
            {"task": "检查是否涉及壳公司/空壳风险", "category": "风险筛查"},
            {"task": "核实注册地址与实际经营地址一致性", "category": "身份核验"},
            {"task": "审查授权签字人身份与权限", "category": "身份核验"},
            {"task": "检查是否在制裁/负面清单范围内", "category": "制裁筛查"},
            {"task": "完成企业风险评估问卷", "category": "风险评估"},
        ],
    },
    {
        "slug": "kyc-nonprofit",
        "name": "非营利组织开户合规检查",
        "category": "KYC开户合规",
        "description": "对 NPO/NGO 类客户的专项合规审查，关注恐怖融资风险",
        "applicable_scenarios": ["慈善机构开户", "NGO开户", "基金会"],
        "items": [
            {"task": "核验非营利组织注册/登记证书", "category": "身份核验", "guidance": "FATF Recommendation 8"},
            {"task": "审查组织章程与宗旨说明书", "category": "背景审查"},
            {"task": "识别理事会成员与管理层身份", "category": "UBO识别"},
            {"task": "审查资金来源渠道与捐赠方名单", "category": "资金来源"},
            {"task": "核实资金用途/项目信息", "category": "资金用途"},
            {"task": "检查捐赠方是否在制裁名单", "category": "制裁筛查"},
            {"task": "评估恐怖融资风险", "category": "风险评估", "guidance": "FATF Recommendation 8"},
            {"task": "年度活动报告审查", "category": "持续监控"},
        ],
    },
    {
        "slug": "kyc-financial-institution",
        "name": "金融机构间开户合规检查",
        "category": "KYC开户合规",
        "description": "代理行/金融机构客户的开户尽职调查",
        "applicable_scenarios": ["代理行关系", "金融机构开户"],
        "items": [
            {"task": "确认对方金融机构监管牌照/注册地", "category": "背景审查", "guidance": "FATF Recommendation 13"},
            {"task": "审查 AML/CFT 合规体系文件", "category": "合规审查", "guidance": "Wolfsberg Group AML Principles"},
            {"task": "获取对方机构的风险自评估报告", "category": "风险评估"},
            {"task": "了解对方客户群体类型与风险特征", "category": "风险评估"},
            {"task": "审查是否在空壳银行清单内", "category": "风险筛查", "guidance": "USA PATRIOT Act §313"},
            {"task": "获取高级管理层批准（禁止空壳银行往来）", "category": "审批"},
            {"task": "定期复审对方 AML 合规状况", "category": "持续监控"},
        ],
    },
    {
        "slug": "kyc-ubor-penetration",
        "name": "受益所有人穿透识别检查清单",
        "category": "KYC开户合规",
        "description": "针对复杂结构的 UBO 穿透识别，符合 OFAC 50%规则与 FATF 标准",
        "applicable_scenarios": ["多层控股公司", "信托结构", "基金结构"],
        "items": [
            {"task": "获取完整股权结构图（至最顶层）", "category": "UBO识别", "guidance": "FATF Recommendation 24"},
            {"task": "识别所有直接持股 ≥25% 的自然人", "category": "UBO识别", "guidance": "OFAC 50 Percent Rule"},
            {"task": "识别通过协议/信托/代持实施控制的自然人", "category": "UBO识别"},
            {"task": "交叉验证受益所有人身份文件", "category": "UBO识别"},
            {"task": "检查受益所有人是否在制裁名单中", "category": "制裁筛查"},
            {"task": "检查是否存在名义股东/代持安排", "category": "风险筛查"},
            {"task": "验证 UBO 声明文件的完整性与一致性", "category": "文档审查"},
            {"task": "评估控制权复杂度与信息透明度", "category": "风险评估"},
        ],
    },
    {
        "slug": "kyc-periodic-review",
        "name": "客户定期复审检查清单",
        "category": "KYC开户合规",
        "description": "按风险等级定期对存量客户进行年度/半年度复审",
        "applicable_scenarios": ["年度合规复审", "触发式复审"],
        "items": [
            {"task": "确认客户基本身份信息有无变更", "category": "身份核验", "guidance": "FATF Recommendation 10"},
            {"task": "更新制裁名单筛查结果", "category": "制裁筛查"},
            {"task": "更新受益所有人信息", "category": "UBO识别"},
            {"task": "更新 PEP 状态", "category": "风险筛查"},
            {"task": "审查交易行为变化与预期是否一致", "category": "交易监控"},
            {"task": "更新风险评级", "category": "风险评估"},
            {"task": "记录复审发现与处置措施", "category": "文档归档"},
            {"task": "确认是否需调整为 EDD 或 SDD", "category": "审批"},
        ],
    },
    {
        "slug": "kyc-sdd-simplified",
        "name": "简化尽职调查（SDD）检查清单",
        "category": "KYC开户合规",
        "description": "低风险客户的简化尽职调查流程",
        "applicable_scenarios": ["上市公司", "政府机构", "低风险国家个人客户"],
        "items": [
            {"task": "确认客户符合 SDD 适用条件", "category": "风险评估", "guidance": "FATF Recommendation 10"},
            {"task": "核验客户身份基本要素", "category": "身份核验"},
            {"task": "执行制裁名单筛查", "category": "制裁筛查"},
            {"task": "记录 SDD 适用理由", "category": "文档归档"},
        ],
    },

    # =====================================================================
    # 供应商准入 (6 templates)
    # =====================================================================
    {
        "slug": "supplier-onboarding-basic",
        "name": "供应商准入基础合规检查",
        "category": "供应商准入",
        "description": "新供应商基础合规尽职调查，涵盖制裁筛查、反贿赂与 ESG",
        "applicable_scenarios": ["新供应商引入", "供应商入库"],
        "items": [
            {"task": "供应商基本信息核验（营业执照、注册地）", "category": "身份核验"},
            {"task": "制裁名单筛查", "category": "制裁筛查"},
            {"task": "最终受益所有人识别", "category": "UBO识别"},
            {"task": "反贿赂/反腐败合规声明获取", "category": "反腐败", "guidance": "FCPA; UK Bribery Act"},
            {"task": "企业社会责任/ESG 政策审查", "category": "ESG"},
            {"task": "信用报告/诉讼记录查询", "category": "背景审查"},
            {"task": "供应商自评问卷完成", "category": "风险评估"},
            {"task": "合规审批", "category": "审批"},
        ],
    },
    {
        "slug": "supplier-export-control",
        "name": "供应商出口管制合规审查",
        "category": "供应商准入",
        "description": "涉及进出口业务的供应商出口管制合规检查",
        "applicable_scenarios": ["涉及美国管制物项的供应商", "军品/双用途供应商"],
        "items": [
            {"task": "确认供应商主要产品/服务及 HS 编码", "category": "物项分类"},
            {"task": "确认供应商是否涉及美国管制物项（ECCN/BIS）", "category": "出口管制", "guidance": "EAR Part 738-774"},
            {"task": "供应商是否在 BIS 实体清单/UVL/DPL 中", "category": "实体筛查"},
            {"task": "供应商是否涉及军事最终用户/用途", "category": "最终用途", "guidance": "EAR §744.21"},
            {"task": "审查供应商对中国出口管制法的合规声明", "category": "中国法规", "guidance": "《出口管制法》2020"},
            {"task": "确认供应商是否涉及 De Minimis/FDPR 规则", "category": "规则适用"},
            {"task": "签署最终用途声明", "category": "文档归档"},
        ],
    },
    {
        "slug": "supplier-forced-labor",
        "name": "供应商强迫劳动审查清单",
        "category": "供应商准入",
        "description": "根据 UFLPA 及供应链尽职调查指令对供应商进行强迫劳动风险评估",
        "applicable_scenarios": ["涉疆供应链", "高风险地区供应商"],
        "items": [
            {"task": "确认供应商所在地及生产区域（是否新疆等高风险地区）", "category": "地域筛查", "guidance": "UFLPA"},
            {"task": "审查供应商用工政策与社保缴纳记录", "category": "劳动合规"},
            {"task": "获取供应商未使用强迫劳动声明", "category": "声明文件"},
            {"task": "实地考察或第三方审计安排", "category": "审计"},
            {"task": "原材料溯源至原产地", "category": "供应链溯源", "guidance": "UFLPA §3"},
            {"task": "建立供应链追溯文档体系", "category": "文档归档"},
            {"task": "合规审批：确认不涉及强迫劳动风险", "category": "审批"},
        ],
    },
    {
        "slug": "supplier-high-risk-region",
        "name": "高风险地区供应商加强审查清单",
        "category": "供应商准入",
        "description": "来自制裁/禁运/高风险国家的供应商加强审查",
        "applicable_scenarios": ["伊朗/朝鲜/叙利亚/克里米亚等地区"],
        "items": [
            {"task": "确认供应商注册地所在国家制裁情况", "category": "制裁筛查", "guidance": "OFAC 制裁计划"},
            {"task": "确认交易是否违反全面制裁/禁运", "category": "制裁审查"},
            {"task": "评估是否可适用许可证例外或豁免", "category": "许可评估"},
            {"task": "获取 OFAC/OF SI 许可证（如需）", "category": "许可申请"},
            {"task": "高级管理层批准", "category": "审批"},
            {"task": "持续监控制裁变化", "category": "持续监控"},
        ],
    },
    {
        "slug": "supplier-anti-bribery",
        "name": "供应商反贿赂合规审查",
        "category": "供应商准入",
        "description": "根据 FCPA/UK Bribery Act/中国反不正当竞争法审查供应商",
        "applicable_scenarios": ["涉及政府客户的供应商", "中间商/代理"],
        "items": [
            {"task": "获取供应商反腐败政策文件", "category": "政策审查", "guidance": "FCPA; UK Bribery Act §7"},
            {"task": "审查供应商与政府官员的关联关系", "category": "利益冲突"},
            {"task": "审查佣金/代理费/咨询费合理性", "category": "费用审查", "guidance": "FCPA 反贿赂条款"},
            {"task": "对第三方代理进行背景调查", "category": "背景审查"},
            {"task": "签署反腐败合规承诺书", "category": "文档归档"},
            {"task": "定期审查供应商合规记录", "category": "持续监控"},
        ],
    },
    {
        "slug": "supplier-annual-review",
        "name": "供应商年度合规复审清单",
        "category": "供应商准入",
        "description": "对存量供应商执行年度合规复审",
        "applicable_scenarios": ["供应商年审", "续约前审查"],
        "items": [
            {"task": "更新制裁名单筛查结果", "category": "制裁筛查"},
            {"task": "更新供应商证照/经营范围变化", "category": "信息更新"},
            {"task": "审查过去一年交易合规性", "category": "交易审查"},
            {"task": "更新 ESG/劳工合规评估", "category": "ESG"},
            {"task": "检查有无新增的负面新闻/诉讼", "category": "背景审查"},
            {"task": "更新风险评级", "category": "风险评估"},
            {"task": "决定续约/暂停/终止", "category": "审批"},
        ],
    },

    # =====================================================================
    # 出口管制 (6 templates)
    # =====================================================================
    {
        "slug": "export-control-first-export",
        "name": "首次出口合规检查清单",
        "category": "出口管制",
        "description": "企业首次出口前的四要素（物项/目的地/最终用户/最终用途）合规判定",
        "applicable_scenarios": ["首次出口", "新产品出口"],
        "items": [
            {"task": "确认产品 HS 编码和 ECCN 分类", "category": "物项分类", "guidance": "EAR Part 738; CCL"},
            {"task": "确认是否为 EAR99 物项", "category": "物项分类", "guidance": "EAR §734.3"},
            {"task": "确认目的地国家分组（A/B/D/E 组）", "category": "目的地", "guidance": "EAR Supplement No.1 to Part 740"},
            {"task": "检查最终用户是否在实体清单/UVL/DPL/SDN 中", "category": "最终用户", "guidance": "BIS Entity List; OFAC SDN"},
            {"task": "确认最终用途是否为军事/大规模杀伤性武器", "category": "最终用途", "guidance": "EAR §744"},
            {"task": "检查许可证例外/豁免适用性", "category": "许可评估", "guidance": "EAR Part 740"},
            {"task": "申请 BIS 出口许可证（如需要）", "category": "许可申请"},
            {"task": "确认中国出口管制法合规要求", "category": "中国法规", "guidance": "《出口管制法》2020"},
            {"task": "签署最终用途声明", "category": "文档归档"},
            {"task": "合规审批与归档", "category": "审批"},
        ],
    },
    {
        "slug": "export-control-de-minimis",
        "name": "De Minimis 规则适用检查清单",
        "category": "出口管制",
        "description": "判断非美国原产产品是否因含有美国管制成分而受 EAR 管辖",
        "applicable_scenarios": ["含有美国原产物项", "混合产品"],
        "items": [
            {"task": "识别产品中所有美国原产成分/技术", "category": "成分识别", "guidance": "EAR §734.4"},
            {"task": "计算美国原产成分价值占比", "category": "计算", "guidance": "EAR §734.4(a)"},
            {"task": "判断美国原产成分是否受 EAR 管制", "category": "管制判定"},
            {"task": "确认 De Minimis 阈值（0%/10%/25%）", "category": "阈值判定", "guidance": "EAR §734.4(d)"},
            {"task": "文档化计算过程与判定结果", "category": "文档归档"},
            {"task": "如超出阈值，重新进行 ECCN 分类", "category": "物项分类"},
        ],
    },
    {
        "slug": "export-control-fdpr",
        "name": "外国直接产品规则（FDPR）检查清单",
        "category": "出口管制",
        "description": "判断在外国生产的产品是否因使用美国技术/软件/设备而受 EAR 管辖",
        "applicable_scenarios": ["使用美国技术的外国产品", "华为FDPR"],
        "items": [
            {"task": "确认产品是否直接使用美国技术/软件生产", "category": "技术来源", "guidance": "EAR §736.2(b)(3)"},
            {"task": "确认产品是否为特定 FDPR 规则涵盖物项", "category": "物项范围", "guidance": "EAR §734.9"},
            {"task": "确认目的地是否为 FDPR 指定国家（如华为清单）", "category": "目的地", "guidance": "EAR §744.11 & 744.23"},
            {"task": "确认最终用户是否为 Entity List Footnote 1 实体", "category": "最终用户"},
            {"task": "如适用 FDPR，重新确认许可证要求", "category": "许可评估"},
            {"task": "文档化 FDPR 分析结论", "category": "文档归档"},
        ],
    },
    {
        "slug": "export-control-technology-transfer",
        "name": "技术转让/视同出口检查清单",
        "category": "出口管制",
        "description": "向外国人在美国境内或跨境技术转移时的合规审查",
        "applicable_scenarios": ["技术许可", "外国雇员接触受控技术", "技术交流"],
        "items": [
            {"task": "确认待转让技术的 ECCN 分类", "category": "物项分类", "guidance": "EAR §734.13"},
            {"task": "确认接收方国籍/最终用户", "category": "最终用户", "guidance": "EAR §734.13(b)"},
            {"task": "判断是否构成「视同出口」(Deemed Export)", "category": "判定"},
            {"task": "确认是否需要 BIS 许可证", "category": "许可评估"},
            {"task": "确认中国出口管制法中「视同出口」要求", "category": "中国法规"},
            {"task": "TAA/MLA 协议签署（如适用）", "category": "文档归档", "guidance": "ITAR §120.22"},
            {"task": "内部技术访问权限管控设置", "category": "内控"},
        ],
    },
    {
        "slug": "export-control-itar",
        "name": "ITAR 军品出口管制检查清单",
        "category": "出口管制",
        "description": "涉及 USML 物项的国防物品/国防服务出口合规审查",
        "applicable_scenarios": ["军工产品出口", "国防技术出口"],
        "items": [
            {"task": "确认物项是否在 USML 清单中", "category": "物项分类", "guidance": "ITAR §121"},
            {"task": "确认是否属于 ITAR 豁免情形", "category": "豁免判定", "guidance": "ITAR §125.4"},
            {"task": "获取 DDTC 出口许可证/协议", "category": "许可申请", "guidance": "ITAR §123"},
            {"task": "确认是否需要国会通知（如涉及重大国防设备）", "category": "通知"},
            {"task": "确认最终用户非制裁/禁止方", "category": "最终用户"},
            {"task": "建立 ITAR 合规内控流程", "category": "内控"},
            {"task": "对相关人员培训 ITAR 合规要求", "category": "培训"},
        ],
    },
    {
        "slug": "export-control-china-law",
        "name": "中国出口管制法合规检查清单",
        "category": "出口管制",
        "description": "根据《中国出口管制法》对出口行为进行合规自查",
        "applicable_scenarios": ["涉及中国管制物项/技术的出口"],
        "items": [
            {"task": "确认出口物项是否在中国出口管制清单内", "category": "物项分类", "guidance": "《出口管制法》第9条"},
            {"task": "确认是否需要申请出口许可证", "category": "许可评估", "guidance": "《出口管制法》第12条"},
            {"task": "确认最终用户和最终用途", "category": "最终用户", "guidance": "《出口管制法》第15条"},
            {"task": "检查最终用户是否在中国不可靠实体清单", "category": "实体筛查", "guidance": "《不可靠实体清单规定》"},
            {"task": "建立内部合规制度（ICP）", "category": "内控", "guidance": "《两用物项出口管制内部合规指南》"},
            {"task": "确认是否需要临时管制/禁运审查", "category": "临时管制"},
            {"task": "保留出口记录和文件至少5年", "category": "文档归档"},
        ],
    },

    # =====================================================================
    # 数据与隐私 (8 templates)
    # =====================================================================
    {
        "slug": "data-privacy-pipl-basic",
        "name": "PIPL 数据处理合规检查清单",
        "category": "数据与隐私",
        "description": "根据《个人信息保护法》对个人信息处理活动进行全面合规自查",
        "applicable_scenarios": ["个人信息处理", "APP/网站运营"],
        "items": [
            {"task": "确认是否有合法基础处理个人信息", "category": "法律基础", "guidance": "PIPL 第13条"},
            {"task": "制定/更新隐私政策并显著性展示", "category": "告知同意", "guidance": "PIPL 第17条"},
            {"task": "获取个人明确/单独同意（如需要）", "category": "告知同意", "guidance": "PIPL 第23/29/39条"},
            {"task": "开展个人信息保护影响评估（PIPIA）", "category": "评估", "guidance": "PIPL 第55条"},
            {"task": "建立数据分类分级制度（一般/重要/核心）", "category": "数据分类", "guidance": "DSL 第21条"},
            {"task": "指定个人信息保护负责人", "category": "组织架构", "guidance": "PIPL 第52条"},
            {"task": "建立数据安全事件应急响应机制", "category": "安全", "guidance": "PIPL 第57条"},
            {"task": "确保数据主体的查阅/更正/删除权通道", "category": "数据主体权利", "guidance": "PIPL 第44-47条"},
        ],
    },
    {
        "slug": "data-export-security-assessment",
        "name": "数据出境安全评估检查清单",
        "category": "数据与隐私",
        "description": "个人信息/重要数据出境前的安全评估申报流程",
        "applicable_scenarios": ["数据出境", "重要数据出境", "CIIO数据出境"],
        "items": [
            {"task": "确定出境数据类型（个人信息/重要数据/CIIO数据）", "category": "数据类型", "guidance": "《数据出境安全评估办法》第4条"},
            {"task": "确认是否触发安全评估门槛", "category": "门槛判定"},
            {"task": "开展数据出境风险自评估", "category": "评估", "guidance": "《数据出境安全评估办法》第5条"},
            {"task": "准备申报材料（自评估报告、法律文件等）", "category": "申报准备"},
            {"task": "向省级网信办提交安全评估申报", "category": "申报", "guidance": "《数据出境安全评估办法》第7条"},
            {"task": "跟踪评估进度（45工作日内完成）", "category": "进度跟踪"},
            {"task": "评估通过后建立持续监控机制", "category": "持续合规"},
        ],
    },
    {
        "slug": "data-export-standard-contract",
        "name": "数据出境标准合同备案清单",
        "category": "数据与隐私",
        "description": "通过签署个人信息出境标准合同完成数据出境合规路径",
        "applicable_scenarios": ["非CIIO", "非重要数据", "未达安全评估门槛"],
        "items": [
            {"task": "确认适用标准合同路径（非CIIO/非重要数据/未达量级）", "category": "适用条件", "guidance": "《个人信息出境标准合同办法》第4条"},
            {"task": "开展个人信息保护影响评估（PIPIA）", "category": "评估"},
            {"task": "签署个人信息出境标准合同", "category": "签约"},
            {"task": "准备备案材料", "category": "备案准备"},
            {"task": "向省级网信办提交备案", "category": "备案", "guidance": "《个人信息出境标准合同办法》第7条"},
            {"task": "跟进备案结果（15工作日内）", "category": "进度跟踪"},
        ],
    },
    {
        "slug": "data-gdpr-compliance",
        "name": "GDPR 合规检查清单",
        "category": "数据与隐私",
        "description": "面向处理欧盟居民数据的企业 GDPR 全量合规自查",
        "applicable_scenarios": ["在欧盟有业务", "处理EU数据主体的数据"],
        "items": [
            {"task": "确认 GDPR 适用性（属地/属人/属事）", "category": "适用性", "guidance": "GDPR Art.3"},
            {"task": "确定法律基础（同意/合同必需/合法利益等）", "category": "法律基础", "guidance": "GDPR Art.6"},
            {"task": "指定欧盟代表（如适用 Art.27）", "category": "组织", "guidance": "GDPR Art.27"},
            {"task": "任命数据保护官 DPO", "category": "组织", "guidance": "GDPR Art.37"},
            {"task": "维护数据处理活动记录 RoPA", "category": "文档", "guidance": "GDPR Art.30"},
            {"task": "实施 DPIA（如适用）", "category": "评估", "guidance": "GDPR Art.35"},
            {"task": "建立数据主体权利响应机制（8项权利）", "category": "数据主体权利", "guidance": "GDPR Art.15-22"},
            {"task": "跨境数据传输机制（SCC/BCR/充分性认定）", "category": "跨境传输", "guidance": "GDPR Art.44-49"},
            {"task": "数据泄露通知机制（72小时内）", "category": "安全", "guidance": "GDPR Art.33-34"},
            {"task": "与数据处理者签署 DPA", "category": "合同", "guidance": "GDPR Art.28"},
        ],
    },
    {
        "slug": "data-ccpa-compliance",
        "name": "CCPA/CPRA 合规检查清单",
        "category": "数据与隐私",
        "description": "面向收集加州居民个人信息的企业 CCPA/CPRA 合规检查",
        "applicable_scenarios": ["美国加州有客户", "年营收≥2500万美元"],
        "items": [
            {"task": "确认企业是否满足 CCPA 适用门槛", "category": "适用性", "guidance": "CCPA §1798.140"},
            {"task": "更新隐私通知（收集/使用/共享/出售类别）", "category": "通知", "guidance": "CCPA §1798.100"},
            {"task": "提供「Do Not Sell or Share My Info」选项", "category": "消费者权利", "guidance": "CPRA §1798.120"},
            {"task": "建立消费者数据访问/删除/更正请求流程", "category": "消费者权利", "guidance": "CCPA §1798.105-106"},
            {"task": "限制敏感个人信息的使用", "category": "敏感数据", "guidance": "CPRA §1798.121"},
            {"task": "审查服务提供商合同（含数据处理条款）", "category": "合同", "guidance": "CCPA §1798.140"},
            {"task": "实施合理的安保措施", "category": "安全"},
        ],
    },
    {
        "slug": "data-dsl-classification",
        "name": "数据安全法分类分级检查清单",
        "category": "数据与隐私",
        "description": "根据《数据安全法》对数据资产进行分类分级评估",
        "applicable_scenarios": ["数据资产盘点", "数据分类分级"],
        "items": [
            {"task": "完成企业数据资产盘点", "category": "数据盘点", "guidance": "DSL 第21条"},
            {"task": "识别一般数据、重要数据和核心数据", "category": "分类分级"},
            {"task": "对重要数据建立目录并上报", "category": "重要数据", "guidance": "《重要数据识别指南》"},
            {"task": "明确各类数据的安全保护等级", "category": "安全定级"},
            {"task": "建立数据安全管理制度", "category": "制度建设"},
            {"task": "指定数据安全负责人和管理机构", "category": "组织架构"},
            {"task": "定期开展数据安全风险评估", "category": "评估", "guidance": "DSL 第30条"},
        ],
    },
    {
        "slug": "data-breach-response",
        "name": "数据泄露应急响应检查清单",
        "category": "数据与隐私",
        "description": "数据安全事件泄露后的应急响应流程",
        "applicable_scenarios": ["数据泄露事件", "安全漏洞"],
        "items": [
            {"task": "确认泄露事件范围和受影响数据类型/数量", "category": "事件评估"},
            {"task": "立即启动应急响应团队", "category": "组织响应"},
            {"task": "72小时内通知监管机构（GDPR）/ 立即通知（PIPL）", "category": "通知", "guidance": "GDPR Art.33; PIPL 第57条"},
            {"task": "通知受影响数据主体", "category": "通知", "guidance": "GDPR Art.34; PIPL 第57条"},
            {"task": "采取补救措施弥补漏洞", "category": "补救"},
            {"task": "保存事件处理记录", "category": "文档归档"},
            {"task": "事后复盘与措施改进", "category": "改进"},
        ],
    },
    {
        "slug": "data-ai-governance",
        "name": "AI 数据治理合规检查清单",
        "category": "数据与隐私",
        "description": "涉及 AI 训练/推理的数据来源合规与算法备案要求",
        "applicable_scenarios": ["AI产品上线", "算法备案", "训练数据合规审查"],
        "items": [
            {"task": "确认训练数据来源合法性（自有/授权/公开）", "category": "数据来源", "guidance": "PIPL 第13条"},
            {"task": "评估训练数据的个人信息去标识化程度", "category": "数据保护"},
            {"task": "完成算法备案（如适用：生成合成/个性化推送等）", "category": "备案", "guidance": "《互联网信息服务算法推荐管理规定》"},
            {"task": "进行算法安全评估", "category": "评估", "guidance": "《生成式人工智能服务管理暂行办法》"},
            {"task": "建立 AI 伦理审查流程", "category": "伦理审查"},
            {"task": "确保用户知情权与退出机制", "category": "用户权利"},
        ],
    },

    # =====================================================================
    # 劳动用工 (5 templates)
    # =====================================================================
    {
        "slug": "labor-employment-contract",
        "name": "劳动合同合规审查清单",
        "category": "劳动用工",
        "description": "劳动合同签订、内容条款、试用期与竞业限制合规审查",
        "applicable_scenarios": ["新员工入职", "合同续签"],
        "items": [
            {"task": "确认合同签订时间（入职1个月内）", "category": "合同签订", "guidance": "《劳动合同法》第10条"},
            {"task": "核实合同必备条款完整性", "category": "内容审查", "guidance": "《劳动合同法》第17条"},
            {"task": "确认试用期期限合法（≤1月/2月/6月）", "category": "试用期", "guidance": "《劳动合同法》第19条"},
            {"task": "审查竞业限制条款（适用人员/期限/补偿金）", "category": "竞业限制", "guidance": "《劳动合同法》第23-24条"},
            {"task": "检查加班工资计算基数与支付方式", "category": "薪酬", "guidance": "《劳动法》第44条"},
            {"task": "确认社会保险登记与缴纳", "category": "社保"},
            {"task": "审查保密条款/知识产权归属条款", "category": "知产"},
            {"task": "核实解除/终止合同条件合法性", "category": "终止", "guidance": "《劳动合同法》第39-48条"},
        ],
    },
    {
        "slug": "labor-employee-handbook",
        "name": "员工手册合规审查清单",
        "category": "劳动用工",
        "description": "员工手册规章制度内容的合规审查与民主程序核查",
        "applicable_scenarios": ["员工手册改版", "规章制度制定"],
        "items": [
            {"task": "确认手册内容不违反法律法规", "category": "内容审查"},
            {"task": "履行民主程序（职工代表大会/工会讨论）", "category": "民主程序", "guidance": "《劳动合同法》第4条"},
            {"task": "向全体员工公示或告知", "category": "公示程序"},
            {"task": "审查考勤制度（工时/加班/休假）", "category": "考勤"},
            {"task": "审查奖惩与纪律处分制度", "category": "奖惩"},
            {"task": "确认反歧视/反骚扰政策", "category": "反歧视"},
            {"task": "确认数据保护与隐私政策条款", "category": "数据保护"},
            {"task": "保存民主程序记录文件", "category": "文档归档"},
        ],
    },
    {
        "slug": "labor-cross-border",
        "name": "跨境劳务派遣合规检查清单",
        "category": "劳动用工",
        "description": "海外派遣/跨境劳务的出入境、社保与税务合规审查",
        "applicable_scenarios": ["海外派遣", "跨境劳务输出"],
        "items": [
            {"task": "确认派遣目的国的签证/工作许可要求", "category": "出入境"},
            {"task": "安排派遣员工的境外社会保险", "category": "社保", "guidance": "社保双边协定（如适用）"},
            {"task": "确认社会保障双边协议适用（免双重缴费）", "category": "社保"},
            {"task": "处理个人境外所得税申报", "category": "税务"},
            {"task": "审查派遣合同条款（薪酬/福利/紧急撤离）", "category": "合同"},
            {"task": "安排派遣员工的安全与医疗保障", "category": "安全保障"},
            {"task": "确认目的国劳动法规合规要求", "category": "当地合规"},
        ],
    },
    {
        "slug": "labor-termination",
        "name": "员工离职与解雇合规检查清单",
        "category": "劳动用工",
        "description": "员工离职/解雇的程序合规与补偿金计算",
        "applicable_scenarios": ["员工辞职", "解雇", "经济性裁员"],
        "items": [
            {"task": "确认离职/解雇法律事由", "category": "事由审查", "guidance": "《劳动合同法》第39条（过失性）"},
            {"task": "计算经济补偿金（N/N+1/2N）", "category": "补偿计算", "guidance": "《劳动合同法》第47/87条"},
            {"task": "确认是否涉及不可解雇情形（三期/工伤/医疗期）", "category": "保护条款", "guidance": "《劳动合同法》第42条"},
            {"task": "提前30天通知或支付代通知金", "category": "通知", "guidance": "《劳动合同法》第40条"},
            {"task": "办理离职手续（结算/证明/档案转移）", "category": "手续", "guidance": "《劳动合同法》第50条"},
            {"task": "确认竞业限制补偿金发放", "category": "竞业限制"},
            {"task": "完成离职面谈与风险警示记录", "category": "文档归档"},
        ],
    },
    {
        "slug": "labor-workplace-safety",
        "name": "安全生产与职业健康合规清单",
        "category": "劳动用工",
        "description": "工作场所安全生产、职业健康与工伤预防合规检查",
        "applicable_scenarios": ["工厂/工地", "安全审查"],
        "items": [
            {"task": "确认安全生产许可证有效性", "category": "证照"},
            {"task": "建立安全生产责任制（主要负责人/安全管理人员）", "category": "制度建设", "guidance": "《安全生产法》第5条"},
            {"task": "落实员工安全生产三级教育培训", "category": "培训", "guidance": "《安全生产法》第28条"},
            {"task": "定期排查安全隐患并记录整改", "category": "隐患排查"},
            {"task": "配置劳动防护用品并监督使用", "category": "防护"},
            {"task": "制定生产安全事故应急预案", "category": "应急", "guidance": "《安全生产法》第80条"},
            {"task": "安排职业健康体检", "category": "健康"},
            {"task": "购买工伤保险", "category": "保险"},
        ],
    },

    # =====================================================================
    # 反腐败/反贿赂 (5 templates)
    # =====================================================================
    {
        "slug": "anti-bribery-policy-review",
        "name": "反腐败政策体系审查清单",
        "category": "反腐败",
        "description": "企业反腐败合规政策框架的完整度审查",
        "applicable_scenarios": ["政策制定", "合规体系搭建"],
        "items": [
            {"task": "确认是否制定书面反腐败政策", "category": "政策文件", "guidance": "FCPA; UK Bribery Act §7"},
            {"task": "礼物与招待政策（限额/审批/记录）", "category": "政策文件", "guidance": "FCPA 反贿赂条款"},
            {"task": "第三方尽调政策", "category": "政策文件"},
            {"task": "政治捐款与慈善捐赠政策", "category": "政策文件"},
            {"task": "利益冲突申报政策", "category": "政策文件"},
            {"task": "反腐败培训覆盖率（全体员工/高管100%）", "category": "培训"},
            {"task": "举报保护与匿名举报渠道", "category": "举报", "guidance": "Dodd-Frank Act §922"},
            {"task": "内部审计轮换计划", "category": "审计"},
        ],
    },
    {
        "slug": "anti-bribery-third-party",
        "name": "第三方反腐败尽职调查清单",
        "category": "反腐败",
        "description": "对代理商/咨询顾问/分销商等第三方的反腐败尽职调查",
        "applicable_scenarios": ["代理合同", "咨询协议", "分销协议"],
        "items": [
            {"task": "识别第三方业务类型与风险评估", "category": "风险评估"},
            {"task": "审查第三方与政府官员的关联关系", "category": "关联关系"},
            {"task": "对第三方所有者/高管进行制裁筛查", "category": "制裁筛查"},
            {"task": "审查佣金/代理费率合理性（市场基准比对）", "category": "费用审查"},
            {"task": "签署反腐败合规承诺书", "category": "文档归档"},
            {"task": "要求提供完整的反腐败合规记录", "category": "背景审查"},
            {"task": "合同包含审计条款（查账权）", "category": "合同条款"},
            {"task": "定期对第三方进行合规复审", "category": "持续监控"},
        ],
    },
    {
        "slug": "anti-bribery-gifts-entertainment",
        "name": "礼物与招待合规审查清单",
        "category": "反腐败",
        "description": "员工向政府官员/商业伙伴赠送礼物及商务招待的合规审查",
        "applicable_scenarios": ["商务宴请", "节日礼物", "差旅安排"],
        "items": [
            {"task": "确认礼物/招待接收方是否为政府官员", "category": "接收方识别", "guidance": "FCPA 反贿赂条款"},
            {"task": "核查礼物价值是否在限额内", "category": "价值审查"},
            {"task": "审查是否有审批记录", "category": "审批"},
            {"task": "确认不涉及交换商业利益/决策影响", "category": "目的审查"},
            {"task": "记录每笔礼物/招待详情", "category": "记录保存"},
            {"task": "检查是否符合当地法律要求", "category": "当地法规"},
        ],
    },
    {
        "slug": "anti-bribery-facilitation-payments",
        "name": "便利费排查与合规清单",
        "category": "反腐败",
        "description": "排查企业是否存在小额便利费支付，并制定合规策略",
        "applicable_scenarios": ["海关清关", "审批加速"],
        "items": [
            {"task": "排查业务中是否曾发生便利费支付", "category": "排查"},
            {"task": "确认便利费在所在管辖区是否合法（FCPA允许/UKBA禁止）", "category": "法律审查", "guidance": "FCPA 便利费例外; UK Bribery Act §6"},
            {"task": "如仍存在便利费，建立审批-记录-会计机制", "category": "内控"},
            {"task": "制定逐步消除便利费的时间表", "category": "策略"},
            {"task": "培训相关员工便利费法律风险", "category": "培训"},
        ],
    },
    {
        "slug": "anti-bribery-mna-due-diligence",
        "name": "并购反腐败尽调清单",
        "category": "反腐败",
        "description": "企业并购/投资前的反腐败与FCPA合规尽职调查",
        "applicable_scenarios": ["并购", "投资", "合资"],
        "items": [
            {"task": "审查目标公司反腐败政策与内控体系", "category": "体系审查"},
            {"task": "核查目标公司历史行政处罚/诉讼记录", "category": "历史审查"},
            {"task": "审查目标公司第三方代理合同", "category": "第三方审查"},
            {"task": "对目标公司关键人员进行背景调查", "category": "背调"},
            {"task": "识别目标公司政府客户/合同比例", "category": "风险评估"},
            {"task": "交易协议中包含继承责任条款", "category": "合同条款"},
            {"task": "交割后合规整合时间表", "category": "整合"},
        ],
    },

    # =====================================================================
    # 境外投资 (4 templates)
    # =====================================================================
    {
        "slug": "overseas-investment-odi",
        "name": "ODI 备案合规检查清单",
        "category": "境外投资",
        "description": "中国企业境外直接投资（ODI）的发改委/商务部/外管局备案流程",
        "applicable_scenarios": ["境外新设公司", "境外并购"],
        "items": [
            {"task": "确认投资是否属于敏感项目（敏感国家/行业）", "category": "项目分类", "guidance": "《企业境外投资管理办法》第13条"},
            {"task": "完成发改委项目核准/备案", "category": "发改委", "guidance": "《企业境外投资管理办法》"},
            {"task": "完成商务部企业境外投资证书申领", "category": "商务部"},
            {"task": "完成外汇管理局外汇登记", "category": "外管局"},
            {"task": "审查目标国投资准入限制（CFIUS/FIRRMA/NSIA等）", "category": "目标国审查"},
            {"task": "开展投资地法律环境尽职调查", "category": "尽调"},
            {"task": "编制合规投资方案与风险应对措施", "category": "方案编制"},
            {"task": "完成 ODI 年报/半年报报送", "category": "后续报告"},
        ],
    },
    {
        "slug": "overseas-investment-cfius",
        "name": "CFIUS 审查应对检查清单",
        "category": "境外投资",
        "description": "中国企业赴美投资面临 CFIUS 国家安全审查的应对准备",
        "applicable_scenarios": ["美国投资", "涉及TID技术/基础设施/数据"],
        "items": [
            {"task": "评估交易是否属于 CFIUS 强制申报范围（TID 业务）", "category": "范围判定", "guidance": "FIRRMA; 31 CFR Part 800"},
            {"task": "审查标的是否涉及关键技术/关键基础设施/敏感个人数据", "category": "TID审查"},
            {"task": "评估是否适用「白名单」豁免国家", "category": "豁免"},
            {"task": "制定缓解协议（Mitigation Agreement）预案", "category": "减缓措施"},
            {"task": "准备自愿申报（Declaration 或 Notice）", "category": "申报准备"},
            {"task": "聘请美国国家安全法律顾问", "category": "法律支持"},
            {"task": "准备应对审查问询问卷", "category": "应对准备"},
        ],
    },
    {
        "slug": "overseas-investment-eu-fdi",
        "name": "欧盟 FDI 审查合规清单",
        "category": "境外投资",
        "description": "对欧盟成员国的外国直接投资 FDI 审查合规准备",
        "applicable_scenarios": ["欧盟投资", "敏感行业并购"],
        "items": [
            {"task": "识别目标欧盟成员国 FDI 审查制度", "category": "审查识别", "guidance": "EU FDI Screening Regulation 2019/452"},
            {"task": "确认投资是否涉及战略行业（国防/能源/通信/AI等）", "category": "行业审查"},
            {"task": "评估投资者是否受外国政府控制/影响", "category": "投资者审查"},
            {"task": "准备投资对安全/公共秩序影响的论证材料", "category": "申报准备"},
            {"task": "提交 FDI 审查申请", "category": "申报"},
            {"task": "关注欧盟层面的合作审查程序", "category": "欧盟协调"},
        ],
    },
    {
        "slug": "overseas-investment-tax-structure",
        "name": "境外投资税务架构合规清单",
        "category": "境外投资",
        "description": "跨境投资架构的税务合规审查 — CFC规则、转让定价、BEPS",
        "applicable_scenarios": ["离岸架构", "跨境并购税务"],
        "items": [
            {"task": "审查投资架构是否存在受控外国企业（CFC）风险", "category": "CFC", "guidance": "《个人所得税法》第8条; 《企业所得税法》第45条"},
            {"task": "评估中间控股公司是否有经济实质", "category": "经济实质"},
            {"task": "审查关联交易转让定价合规（BEPS 行动计划13）", "category": "转让定价", "guidance": "OECD BEPS Action 13"},
            {"task": "确认是否触发 CRS 信息交换", "category": "CRS"},
            {"task": "源泉扣缴税（股息/利息/特许权使用费）合规", "category": "预提税"},
            {"task": "利用双边税收协定减免预提税", "category": "税收协定"},
            {"task": "编制国别报告（CbCR）（如适用）", "category": "报告"},
        ],
    },

    # =====================================================================
    # 知识产权 (5 templates)
    # =====================================================================
    {
        "slug": "ip-patent-filing",
        "name": "专利申请合规检查清单",
        "category": "知识产权",
        "description": "专利申请前的内部审查 — 可专利性、发明人认定、保密审查",
        "applicable_scenarios": ["境内专利申请", "PCT申请"],
        "items": [
            {"task": "完成发明人认定与权属确认", "category": "权利归属"},
            {"task": "在申请日前是否已经公开发明", "category": "新颖性", "guidance": "《专利法》第22条"},
            {"task": "启动技术交底书撰写与审核", "category": "交底书"},
            {"task": "进行现有技术检索/查新", "category": "检索"},
            {"task": "判断是否需保密审查（发明在中国完成）", "category": "保密审查", "guidance": "《专利法》第20条"},
            {"task": "确定申请策略（国内/PCT/巴黎公约）", "category": "布局"},
            {"task": "确认发明人报酬/奖励安排", "category": "发明人权益", "guidance": "《专利法》第15条"},
            {"task": "审核专利申请文本质量", "category": "文本审核"},
        ],
    },
    {
        "slug": "ip-trademark-registration",
        "name": "商标注册合规检查清单",
        "category": "知识产权",
        "description": "商标申请前的可注册性审查、类别选择与海外布局",
        "applicable_scenarios": ["国内商标注册", "马德里国际注册"],
        "items": [
            {"task": "商标显著性审查（是否属于绝对禁止条款）", "category": "显著性", "guidance": "《商标法》第11条"},
            {"task": "检查是否与在先权利冲突", "category": "冲突检索"},
            {"task": "确定商品/服务类别（尼斯分类）", "category": "分类"},
            {"task": "海外目标市场商标布局（马德里/逐一申请）", "category": "海外布局"},
            {"task": "评估是否需要在中文/当地语言商标注册", "category": "本地化"},
            {"task": "保留首次使用证据", "category": "使用证据"},
            {"task": "制定商标维权监控方案", "category": "维权"},
        ],
    },
    {
        "slug": "ip-license-audit",
        "name": "知识产权许可合规审计清单",
        "category": "知识产权",
        "description": "企业许可使用的知识产权合规审计（开源软件、专利池、商业许可）",
        "applicable_scenarios": ["软件许可审计", "专利许可审计", "开源合规"],
        "items": [
            {"task": "盘点所有在用第三方软件/库清单", "category": "使用清单"},
            {"task": "确认每个软件的开源许可证类型（GPL/MIT/Apache等）", "category": "许可证审查"},
            {"task": "评估 Copyleft 许可证合规风险（GPL/AGPL）", "category": "风险审查"},
            {"task": "检查商业软件许可数量是否超出授权", "category": "授权审查"},
            {"task": "审查专利许可协议到期情况", "category": "专利许可"},
            {"task": "构建软件物料清单 SBOM", "category": "SBOM"},
            {"task": "建立开源合规审批流程", "category": "制度建设"},
        ],
    },
    {
        "slug": "ip-trade-secret",
        "name": "商业秘密保护合规检查清单",
        "category": "知识产权",
        "description": "商业秘密识别、保密措施与员工离职脱密管理",
        "applicable_scenarios": ["商业秘密识别", "员工离职", "竞业限制"],
        "items": [
            {"task": "完成商业秘密资产清单与分级", "category": "资产识别", "guidance": "《反不正当竞争法》第9条"},
            {"task": "检查技术秘密的物理隔离措施", "category": "物理安全"},
            {"task": "审查信息系统的访问控制与日志审计", "category": "技术安全"},
            {"task": "确认涉密员工的保密协议签署", "category": "协议"},
            {"task": "建立员工离职脱密程序", "category": "离职管理"},
            {"task": "检查与外协方的保密协议", "category": "外部合作"},
            {"task": "定期商业秘密培训", "category": "培训"},
        ],
    },
    {
        "slug": "ip-cross-border-enforcement",
        "name": "海外知识产权维权清单",
        "category": "知识产权",
        "description": "应对海外知识产权纠纷（侵权警告函、337调查、展会侵权）",
        "applicable_scenarios": ["海外被诉侵权", "337调查", "展会扣押"],
        "items": [
            {"task": "立即通知公司法务与知识产权顾问", "category": "应急响应"},
            {"task": "评估侵权指控的可成立性（FTO分析复核）", "category": "技术分析"},
            {"task": "制定应诉/和解/规避设计策略", "category": "策略制定"},
            {"task": "收集不侵权/无效证据", "category": "证据收集"},
            {"task": "聘请目标国知识产权诉讼律师", "category": "法律支持"},
            {"task": "评估对业务的影响（市场份额/客户关系）", "category": "影响评估"},
            {"task": "如涉及337调查，确认答辩时限（20天）", "category": "337调查", "guidance": "19 USC §1337"},
        ],
    },

    # =====================================================================
    # ESG 合规 (4 templates)
    # =====================================================================
    {
        "slug": "esg-disclosure-readiness",
        "name": "ESG 信息披露准备清单",
        "category": "ESG合规",
        "description": "上市公司 ESG 报告编制前的信息披露准备与指标核查",
        "applicable_scenarios": ["ESG报告编制", "披露合规"],
        "items": [
            {"task": "确定适用的 ESG 披露标准（GRI/SASB/TCFD/ISSB）", "category": "标准选择"},
            {"task": "收集环境指标数据（碳排放/能耗/水资源/废弃物）", "category": "环境", "guidance": "GRI 300系列"},
            {"task": "收集社会指标数据（员工/供应链/社区）", "category": "社会", "guidance": "GRI 400系列"},
            {"task": "收集治理指标数据（董事会/反腐败/风险管理）", "category": "治理", "guidance": "GRI 200系列"},
            {"task": "进行实质性议题评估（Materiality Assessment）", "category": "评估"},
            {"task": "碳核算（范围1/2/3）", "category": "碳核算", "guidance": "GHG Protocol"},
            {"task": "第三方鉴证安排", "category": "鉴证"},
            {"task": "编制并审核 ESG 报告", "category": "报告编制"},
        ],
    },
    {
        "slug": "esg-supply-chain",
        "name": "供应链 ESG 尽职调查清单",
        "category": "ESG合规",
        "description": "对供应链中的 ESG 风险进行识别、评估和管理",
        "applicable_scenarios": ["供应商ESG审查", "德国供应链法适用"],
        "items": [
            {"task": "识别供应链中的高风险环节（人权/环境/腐败）", "category": "风险识别", "guidance": "德国《供应链尽职调查法》(LkSG)"},
            {"task": "对一级供应商进行 ESG 问卷评估", "category": "评估"},
            {"task": "审查供应商的劳工权益保障（童工/强迫劳动/最低工资）", "category": "劳工"},
            {"task": "审查供应商环境合规（排污许可/危废处理）", "category": "环境"},
            {"task": "建立供应商 ESG 风险分级制度", "category": "分级"},
            {"task": "制定纠正行动计划（CAP）", "category": "改进"},
            {"task": "年度供应链 ESG 报告", "category": "报告"},
        ],
    },
    {
        "slug": "esg-eu-taxonomy",
        "name": "欧盟分类法合规检查清单",
        "category": "ESG合规",
        "description": "企业在欧盟经营是否符合 EU Taxonomy 可持续活动分类",
        "applicable_scenarios": ["欧盟经营企业", "绿色金融"],
        "items": [
            {"task": "识别企业经济活动是否属于 EU Taxonomy 覆盖范围", "category": "范围识别", "guidance": "EU Taxonomy Regulation 2020/852"},
            {"task": "评估是否对至少一个环境目标有实质性贡献", "category": "实质性贡献"},
            {"task": "确认是否对其他环境目标无重大损害（DNSH）", "category": "DNSH"},
            {"task": "确认是否符合最低社会保障标准", "category": "社会保障", "guidance": "OECD Guidelines; UN Guiding Principles"},
            {"task": "计算合格/符合分类法的营收/CapEx/OpEx 比例", "category": "指标计算"},
            {"task": "编制符合 EU Taxonomy 的披露文件", "category": "披露"},
        ],
    },
    {
        "slug": "esg-carbon-neutrality",
        "name": "碳中和合规路线图清单",
        "category": "ESG合规",
        "description": "企业碳中和目标的制定、路径规划与合规排放交易",
        "applicable_scenarios": ["碳中和", "碳交易", "CBAM"],
        "items": [
            {"task": "完成基准年碳排放清单（范围1/2/3）", "category": "碳核算", "guidance": "GHG Protocol"},
            {"task": "设定科学碳目标（SBTi验证）", "category": "目标设定"},
            {"task": "制定减排路线图（能效/可再生能源/供应链）", "category": "路径规划"},
            {"task": "评估碳抵消/碳信用的合规性", "category": "碳抵消"},
            {"task": "确认是否受 EU CBAM 碳边境调节机制影响", "category": "CBAM", "guidance": "EU CBAM Regulation 2023/956"},
            {"task": "完成 CBAM 季度报告（如适用）", "category": "CBAM报告"},
            {"task": "年度碳中和进展披露", "category": "披露"},
        ],
    },

    # =====================================================================
    # 税务合规 (4 templates)
    # =====================================================================
    {
        "slug": "tax-transfer-pricing",
        "name": "转让定价合规检查清单",
        "category": "税务合规",
        "description": "关联交易的转让定价文档准备与独立交易原则合规检查",
        "applicable_scenarios": ["关联交易", "跨境交易"],
        "items": [
            {"task": "识别所有关联方及关联交易类型", "category": "关联方识别"},
            {"task": "进行功能风险分析", "category": "功能分析"},
            {"task": "选择最合适的转让定价方法（CUP/RPM/CPM/TNMM/PSM）", "category": "方法选择"},
            {"task": "准备基准分析/可比公司搜索", "category": "基准分析"},
            {"task": "编制主体文档与本地文档", "category": "文档编制", "guidance": "OECD BEPS Action 13; 国家税务总局公告2016年第42号"},
            {"task": "编制国别报告（CbCR）（如适用）", "category": "国别报告"},
            {"task": "确认关联交易定价是否在合理区间内", "category": "定价审查"},
        ],
    },
    {
        "slug": "tax-cross-border-wht",
        "name": "跨境预提税合规检查清单",
        "category": "税务合规",
        "description": "跨境股息/利息/特许权使用费的预提税处理",
        "applicable_scenarios": ["境外付汇", "集团内部资金调配"],
        "items": [
            {"task": "确认支付类型（股息/利息/特许权使用费/服务费）", "category": "支付类型"},
            {"task": "确定国内法预提税率", "category": "税率确认"},
            {"task": "检查税收协定是否适用更优惠税率", "category": "税收协定"},
            {"task": "准备享受协定待遇的申请文件", "category": "申请文件"},
            {"task": "审查受益所有人认定", "category": "受益所有人", "guidance": "国家税务总局公告2018年第9号"},
            {"task": "完成预提税申报与代扣代缴", "category": "申报"},
            {"task": "保留完税凭证与合规文档", "category": "文档归档"},
        ],
    },
    {
        "slug": "tax-vat-export",
        "name": "出口退税合规检查清单",
        "category": "税务合规",
        "description": "出口货物增值税退税的合规申报与单证准备",
        "applicable_scenarios": ["出口贸易", "外贸企业"],
        "items": [
            {"task": "确认出口货物属于退税范围（非禁止/限制类）", "category": "范围确认"},
            {"task": "确认出口退税率", "category": "税率确认"},
            {"task": "收集出口报关单", "category": "单证"},
            {"task": "收集增值税专用发票/海关进口增值税专用缴款书", "category": "单证"},
            {"task": "办理出口收汇核销", "category": "核销"},
            {"task": "完成出口退税申报", "category": "申报"},
            {"task": "出口退税单证备案（5年保存期）", "category": "文档归档"},
        ],
    },
    {
        "slug": "tax-digital-economy",
        "name": "数字经济税收合规清单",
        "category": "税务合规",
        "description": "跨国数字服务/电商的数字服务税与经济实质要求",
        "applicable_scenarios": ["跨境电商", "数字服务", "SaaS出口"],
        "items": [
            {"task": "确认销售是否属于数字服务", "category": "业务分类"},
            {"task": "审查目标国数字服务税（DST）适用门槛", "category": "DST"},
            {"task": "确认增值税 GST/VAT 在消费地注册义务", "category": "增值税注册"},
            {"task": "审查海外实体是否构成常设机构（PE）", "category": "PE风险"},
            {"task": "评估 Pillar Two 全球最低税率影响", "category": "Pillar Two", "guidance": "OECD Pillar Two GloBE Rules"},
            {"task": "确认经济实质要求是否满足", "category": "经济实质"},
        ],
    },

    # =====================================================================
    # 反垄断 (2 templates)
    # =====================================================================
    {
        "slug": "antitrust-merger-filing",
        "name": "经营者集中申报检查清单",
        "category": "反垄断",
        "description": "企业并购/合资涉及经营者集中申报的合规审议",
        "applicable_scenarios": ["并购", "合资", "股权收购"],
        "items": [
            {"task": "计算交易参与方全球/中国营业额", "category": "营业额计算", "guidance": "《国务院关于经营者集中申报标准的规定》第3条"},
            {"task": "确认是否达到申报门槛", "category": "门槛判定"},
            {"task": "审查交易是否导致控制权变化", "category": "控制权判定", "guidance": "《反垄断法》第26条"},
            {"task": "评估相关市场界定是否合理", "category": "市场界定"},
            {"task": "进行竞争影响分析（HHI指数/市场集中度）", "category": "竞争分析"},
            {"task": "如涉及多管辖区，确定申报国家", "category": "多辖区"},
            {"task": "向国家市场监管总局提交申报", "category": "申报"},
            {"task": "关注简易程序/普通程序适用", "category": "程序选择"},
        ],
    },
    {
        "slug": "antitrust-compliance-program",
        "name": "反垄断合规体系审查清单",
        "category": "反垄断",
        "description": "企业反垄断合规制度体系搭建与运营审查",
        "applicable_scenarios": ["合规体系搭建", "年审"],
        "items": [
            {"task": "确认是否制定了反垄断合规政策", "category": "政策文件", "guidance": "《经营者反垄断合规指南》"},
            {"task": "禁止横向垄断协议（价格固定/划分市场/限制产量）", "category": "协议审查"},
            {"task": "审查纵向限制（转售价格维持/RPM）风险", "category": "协议审查", "guidance": "《反垄断法》第18条"},
            {"task": "评估市场支配地位及滥用风险", "category": "滥用风险", "guidance": "《反垄断法》第22-24条"},
            {"task": "行业协会参与合规审查", "category": "行业协会"},
            {"task": "员工反垄断培训计划", "category": "培训"},
            {"task": "建立举报与宽大制度内部流程", "category": "宽大制度"},
        ],
    },

    # =====================================================================
    # 产品质量 (2 templates)
    # =====================================================================
    {
        "slug": "product-quality-certification",
        "name": "产品市场准入认证清单",
        "category": "产品质量",
        "description": "产品出口目标市场所需的产品认证与合规标识检查",
        "applicable_scenarios": ["产品出口", "新品上市"],
        "items": [
            {"task": "确认目标市场强制认证要求（CE/FCC/UL/CCC等）", "category": "认证识别"},
            {"task": "选择认可实验室进行产品测试", "category": "测试"},
            {"task": "准备技术文档（TCF）", "category": "文档准备"},
            {"task": "获取 CE 符合性声明（EU 市场）", "category": "CE认证"},
            {"task": "检查产品标识/标签合规（安全/环保/能效）", "category": "标签"},
            {"task": "确认是否需 RoHS / REACH 合规", "category": "化学合规"},
            {"task": "保留合规证书与技术文件（10年保存期）", "category": "文档归档"},
        ],
    },
    {
        "slug": "product-quality-recall",
        "name": "产品召回应急合规清单",
        "category": "产品质量",
        "description": "发现产品质量安全问题后的召回决策与执行流程",
        "applicable_scenarios": ["产品缺陷", "安全事故", "监管抽查不合格"],
        "items": [
            {"task": "确认产品缺陷类型（安全/合规/质量）及严重程度", "category": "缺陷评估"},
            {"task": "启动产品召回决策委员会", "category": "组织响应"},
            {"task": "向监管部门报告（如强制要求）", "category": "监管报告", "guidance": "《缺陷消费品召回管理办法》"},
            {"task": "制定召回计划（范围/方式/时间表）", "category": "计划制定"},
            {"task": "发布召回公告（网站/媒体/经销商渠道）", "category": "公告"},
            {"task": "建立消费者联系与退换/维修渠道", "category": "消费者服务"},
            {"task": "追溯缺陷根因并实施预防措施", "category": "改进"},
            {"task": "召回行动总结报告", "category": "报告"},
        ],
    },

    # =====================================================================
    # 供应链合规 (2 templates)
    # =====================================================================
    {
        "slug": "supply-chain-uflpa",
        "name": "UFLPA 供应链合规溯源清单",
        "category": "供应链合规",
        "description": "面向美国进口的 UFLPA 执法 — 供应链全链路溯源与合规文件准备",
        "applicable_scenarios": ["对美国出口", "涉疆供应链"],
        "items": [
            {"task": "完成全链路供应链映射（原材料→零部件→成品）", "category": "供应链映射", "guidance": "UFLPA"},
            {"task": "识别供应链中所有位于新疆的节点", "category": "地域识别"},
            {"task": "追溯关键原材料来源至矿山/农田级别", "category": "原材料溯源", "guidance": "UFLPA §3"},
            {"task": "收集供应商未使用强迫劳动声明", "category": "声明收集"},
            {"task": "实施供应链审计（包括突击检查）", "category": "审计"},
            {"task": "制定并实施强迫劳动预防政策", "category": "制度建设"},
            {"task": "准备 CBP 可反驳推定材料", "category": "申报材料"},
            {"task": "建立持续供应链监控预警机制", "category": "持续监控"},
        ],
    },
    {
        "slug": "supply-chain-conflict-minerals",
        "name": "冲突矿产合规检查清单",
        "category": "供应链合规",
        "description": "Dodd-Frank 1502 冲突矿产（3TG）合规 — 供应链尽职调查与报告",
        "applicable_scenarios": ["SEC申报企业", "电子产品/汽车供应链"],
        "items": [
            {"task": "确认产品是否含有 3TG 矿产（锡/钽/钨/金）", "category": "矿产识别", "guidance": "Dodd-Frank Act §1502"},
            {"task": "开展供应链 RCOI（原产国调查）", "category": "RCOI"},
            {"task": "对高风险供应商进行尽职调查（OECD 5步框架）", "category": "尽调", "guidance": "OECD Due Diligence Guidance"},
            {"task": "供应商填写 CMRT/EMRT 模板", "category": "模板收集"},
            {"task": "评估冶炼厂/精炼厂合规状态（RMAP 合规名单）", "category": "冶炼厂审查"},
            {"task": "编制冲突矿产报告（CMR）", "category": "报告编制"},
            {"task": "提交 SD 表格至 SEC", "category": "SEC申报"},
        ],
    },
]


def main():
    for tmpl in TEMPLATES:
        slug = tmpl["slug"]
        filepath = OUTPUT_DIR / f"{slug}.json"
        with filepath.open("w", encoding="utf-8") as f:
            json.dump(tmpl, f, ensure_ascii=False, indent=2)
        print(f"  ✓ {slug} ({tmpl['name']}) — {len(tmpl.get('items', []))} items")

    print(f"\nGenerated {len(TEMPLATES)} templates in {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
