/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as WorkspacesRouteImport } from "./routes/workspaces"
import { Route as UserSettingsRouteImport } from "./routes/user-settings"
import { Route as SelectTenantRouteImport } from "./routes/select-tenant"
import { Route as RegularTasksRouteImport } from "./routes/regular-tasks"
import { Route as NoTenantRouteImport } from "./routes/no-tenant"
import { Route as MemoryRouteImport } from "./routes/memory"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as FilesRouteImport } from "./routes/files"
import { Route as ExpertsRouteImport } from "./routes/experts"
import { Route as AutomationRouteImport } from "./routes/automation"
import { Route as AuditRouteImport } from "./routes/audit"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as WorkspaceWorkspaceIdRouteImport } from "./routes/workspace.$workspaceId"
import { Route as TempTaskIdRouteImport } from "./routes/temp.$taskId"
import { Route as SharedReportTokenRouteImport } from "./routes/shared-report.$token"
import { Route as ShareShareIdRouteImport } from "./routes/share.$shareId"
import { Route as SettingsDevicesRouteImport } from "./routes/settings.devices"
import { Route as ExpertsExpertIdRouteImport } from "./routes/experts.$expertId"
import { Route as WorkspaceWorkspaceIdIndexRouteImport } from "./routes/workspace.$workspaceId.index"
import { Route as WorkspaceWorkspaceIdTraceRouteImport } from "./routes/workspace.$workspaceId.trace"
import { Route as WorkspaceWorkspaceIdMonitoringRouteImport } from "./routes/workspace.$workspaceId.monitoring"
import { Route as SettingsSecuritySandboxRouteImport } from "./routes/settings.security.sandbox"
import { Route as WorkspaceWorkspaceIdTaskTaskIdRouteImport } from "./routes/workspace.$workspaceId.task.$taskId"

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: "/workspaces",
  path: "/workspaces",
  getParentRoute: () => rootRouteImport,
} as any)
const UserSettingsRoute = UserSettingsRouteImport.update({
  id: "/user-settings",
  path: "/user-settings",
  getParentRoute: () => rootRouteImport,
} as any)
const SelectTenantRoute = SelectTenantRouteImport.update({
  id: "/select-tenant",
  path: "/select-tenant",
  getParentRoute: () => rootRouteImport,
} as any)
const RegularTasksRoute = RegularTasksRouteImport.update({
  id: "/regular-tasks",
  path: "/regular-tasks",
  getParentRoute: () => rootRouteImport,
} as any)
const NoTenantRoute = NoTenantRouteImport.update({
  id: "/no-tenant",
  path: "/no-tenant",
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: "/memory",
  path: "/memory",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: "/files",
  path: "/files",
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsRoute = ExpertsRouteImport.update({
  id: "/experts",
  path: "/experts",
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: "/automation",
  path: "/automation",
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: "/audit",
  path: "/audit",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceIdRoute = WorkspaceWorkspaceIdRouteImport.update({
  id: "/workspace/$workspaceId",
  path: "/workspace/$workspaceId",
  getParentRoute: () => rootRouteImport,
} as any)
const TempTaskIdRoute = TempTaskIdRouteImport.update({
  id: "/temp/$taskId",
  path: "/temp/$taskId",
  getParentRoute: () => rootRouteImport,
} as any)
const SharedReportTokenRoute = SharedReportTokenRouteImport.update({
  id: "/shared-report/$token",
  path: "/shared-report/$token",
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: "/share/$shareId",
  path: "/share/$shareId",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDevicesRoute = SettingsDevicesRouteImport.update({
  id: "/settings/devices",
  path: "/settings/devices",
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsExpertIdRoute = ExpertsExpertIdRouteImport.update({
  id: "/$expertId",
  path: "/$expertId",
  getParentRoute: () => ExpertsRoute,
} as any)
const WorkspaceWorkspaceIdIndexRoute =
  WorkspaceWorkspaceIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)
const WorkspaceWorkspaceIdTraceRoute =
  WorkspaceWorkspaceIdTraceRouteImport.update({
    id: "/trace",
    path: "/trace",
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)
const WorkspaceWorkspaceIdMonitoringRoute =
  WorkspaceWorkspaceIdMonitoringRouteImport.update({
    id: "/monitoring",
    path: "/monitoring",
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)
const SettingsSecuritySandboxRoute = SettingsSecuritySandboxRouteImport.update({
  id: "/settings/security/sandbox",
  path: "/settings/security/sandbox",
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceIdTaskTaskIdRoute =
  WorkspaceWorkspaceIdTaskTaskIdRouteImport.update({
    id: "/task/$taskId",
    path: "/task/$taskId",
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/audit": typeof AuditRoute
  "/automation": typeof AutomationRoute
  "/experts": typeof ExpertsRouteWithChildren
  "/files": typeof FilesRoute
  "/login": typeof LoginRoute
  "/memory": typeof MemoryRoute
  "/no-tenant": typeof NoTenantRoute
  "/regular-tasks": typeof RegularTasksRoute
  "/select-tenant": typeof SelectTenantRoute
  "/user-settings": typeof UserSettingsRoute
  "/workspaces": typeof WorkspacesRoute
  "/experts/$expertId": typeof ExpertsExpertIdRoute
  "/settings/devices": typeof SettingsDevicesRoute
  "/share/$shareId": typeof ShareShareIdRoute
  "/shared-report/$token": typeof SharedReportTokenRoute
  "/temp/$taskId": typeof TempTaskIdRoute
  "/workspace/$workspaceId": typeof WorkspaceWorkspaceIdRouteWithChildren
  "/settings/security/sandbox": typeof SettingsSecuritySandboxRoute
  "/workspace/$workspaceId/monitoring": typeof WorkspaceWorkspaceIdMonitoringRoute
  "/workspace/$workspaceId/trace": typeof WorkspaceWorkspaceIdTraceRoute
  "/workspace/$workspaceId/": typeof WorkspaceWorkspaceIdIndexRoute
  "/workspace/$workspaceId/task/$taskId": typeof WorkspaceWorkspaceIdTaskTaskIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/audit": typeof AuditRoute
  "/automation": typeof AutomationRoute
  "/experts": typeof ExpertsRouteWithChildren
  "/files": typeof FilesRoute
  "/login": typeof LoginRoute
  "/memory": typeof MemoryRoute
  "/no-tenant": typeof NoTenantRoute
  "/regular-tasks": typeof RegularTasksRoute
  "/select-tenant": typeof SelectTenantRoute
  "/user-settings": typeof UserSettingsRoute
  "/workspaces": typeof WorkspacesRoute
  "/experts/$expertId": typeof ExpertsExpertIdRoute
  "/settings/devices": typeof SettingsDevicesRoute
  "/share/$shareId": typeof ShareShareIdRoute
  "/shared-report/$token": typeof SharedReportTokenRoute
  "/temp/$taskId": typeof TempTaskIdRoute
  "/settings/security/sandbox": typeof SettingsSecuritySandboxRoute
  "/workspace/$workspaceId/monitoring": typeof WorkspaceWorkspaceIdMonitoringRoute
  "/workspace/$workspaceId/trace": typeof WorkspaceWorkspaceIdTraceRoute
  "/workspace/$workspaceId": typeof WorkspaceWorkspaceIdIndexRoute
  "/workspace/$workspaceId/task/$taskId": typeof WorkspaceWorkspaceIdTaskTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/audit": typeof AuditRoute
  "/automation": typeof AutomationRoute
  "/experts": typeof ExpertsRouteWithChildren
  "/files": typeof FilesRoute
  "/login": typeof LoginRoute
  "/memory": typeof MemoryRoute
  "/no-tenant": typeof NoTenantRoute
  "/regular-tasks": typeof RegularTasksRoute
  "/select-tenant": typeof SelectTenantRoute
  "/user-settings": typeof UserSettingsRoute
  "/workspaces": typeof WorkspacesRoute
  "/experts/$expertId": typeof ExpertsExpertIdRoute
  "/settings/devices": typeof SettingsDevicesRoute
  "/share/$shareId": typeof ShareShareIdRoute
  "/shared-report/$token": typeof SharedReportTokenRoute
  "/temp/$taskId": typeof TempTaskIdRoute
  "/workspace/$workspaceId": typeof WorkspaceWorkspaceIdRouteWithChildren
  "/settings/security/sandbox": typeof SettingsSecuritySandboxRoute
  "/workspace/$workspaceId/monitoring": typeof WorkspaceWorkspaceIdMonitoringRoute
  "/workspace/$workspaceId/trace": typeof WorkspaceWorkspaceIdTraceRoute
  "/workspace/$workspaceId/": typeof WorkspaceWorkspaceIdIndexRoute
  "/workspace/$workspaceId/task/$taskId": typeof WorkspaceWorkspaceIdTaskTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/audit"
    | "/automation"
    | "/experts"
    | "/files"
    | "/login"
    | "/memory"
    | "/no-tenant"
    | "/regular-tasks"
    | "/select-tenant"
    | "/user-settings"
    | "/workspaces"
    | "/experts/$expertId"
    | "/settings/devices"
    | "/share/$shareId"
    | "/shared-report/$token"
    | "/temp/$taskId"
    | "/workspace/$workspaceId"
    | "/settings/security/sandbox"
    | "/workspace/$workspaceId/monitoring"
    | "/workspace/$workspaceId/trace"
    | "/workspace/$workspaceId/"
    | "/workspace/$workspaceId/task/$taskId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/audit"
    | "/automation"
    | "/experts"
    | "/files"
    | "/login"
    | "/memory"
    | "/no-tenant"
    | "/regular-tasks"
    | "/select-tenant"
    | "/user-settings"
    | "/workspaces"
    | "/experts/$expertId"
    | "/settings/devices"
    | "/share/$shareId"
    | "/shared-report/$token"
    | "/temp/$taskId"
    | "/settings/security/sandbox"
    | "/workspace/$workspaceId/monitoring"
    | "/workspace/$workspaceId/trace"
    | "/workspace/$workspaceId"
    | "/workspace/$workspaceId/task/$taskId"
  id:
    | "__root__"
    | "/"
    | "/audit"
    | "/automation"
    | "/experts"
    | "/files"
    | "/login"
    | "/memory"
    | "/no-tenant"
    | "/regular-tasks"
    | "/select-tenant"
    | "/user-settings"
    | "/workspaces"
    | "/experts/$expertId"
    | "/settings/devices"
    | "/share/$shareId"
    | "/shared-report/$token"
    | "/temp/$taskId"
    | "/workspace/$workspaceId"
    | "/settings/security/sandbox"
    | "/workspace/$workspaceId/monitoring"
    | "/workspace/$workspaceId/trace"
    | "/workspace/$workspaceId/"
    | "/workspace/$workspaceId/task/$taskId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  AutomationRoute: typeof AutomationRoute
  ExpertsRoute: typeof ExpertsRouteWithChildren
  FilesRoute: typeof FilesRoute
  LoginRoute: typeof LoginRoute
  MemoryRoute: typeof MemoryRoute
  NoTenantRoute: typeof NoTenantRoute
  RegularTasksRoute: typeof RegularTasksRoute
  SelectTenantRoute: typeof SelectTenantRoute
  UserSettingsRoute: typeof UserSettingsRoute
  WorkspacesRoute: typeof WorkspacesRoute
  SettingsDevicesRoute: typeof SettingsDevicesRoute
  ShareShareIdRoute: typeof ShareShareIdRoute
  SharedReportTokenRoute: typeof SharedReportTokenRoute
  TempTaskIdRoute: typeof TempTaskIdRoute
  WorkspaceWorkspaceIdRoute: typeof WorkspaceWorkspaceIdRouteWithChildren
  SettingsSecuritySandboxRoute: typeof SettingsSecuritySandboxRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/workspaces": {
      id: "/workspaces"
      path: "/workspaces"
      fullPath: "/workspaces"
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/user-settings": {
      id: "/user-settings"
      path: "/user-settings"
      fullPath: "/user-settings"
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/select-tenant": {
      id: "/select-tenant"
      path: "/select-tenant"
      fullPath: "/select-tenant"
      preLoaderRoute: typeof SelectTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/regular-tasks": {
      id: "/regular-tasks"
      path: "/regular-tasks"
      fullPath: "/regular-tasks"
      preLoaderRoute: typeof RegularTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/no-tenant": {
      id: "/no-tenant"
      path: "/no-tenant"
      fullPath: "/no-tenant"
      preLoaderRoute: typeof NoTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/memory": {
      id: "/memory"
      path: "/memory"
      fullPath: "/memory"
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/files": {
      id: "/files"
      path: "/files"
      fullPath: "/files"
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/experts": {
      id: "/experts"
      path: "/experts"
      fullPath: "/experts"
      preLoaderRoute: typeof ExpertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/automation": {
      id: "/automation"
      path: "/automation"
      fullPath: "/automation"
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/audit": {
      id: "/audit"
      path: "/audit"
      fullPath: "/audit"
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/workspace/$workspaceId": {
      id: "/workspace/$workspaceId"
      path: "/workspace/$workspaceId"
      fullPath: "/workspace/$workspaceId"
      preLoaderRoute: typeof WorkspaceWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/temp/$taskId": {
      id: "/temp/$taskId"
      path: "/temp/$taskId"
      fullPath: "/temp/$taskId"
      preLoaderRoute: typeof TempTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/shared-report/$token": {
      id: "/shared-report/$token"
      path: "/shared-report/$token"
      fullPath: "/shared-report/$token"
      preLoaderRoute: typeof SharedReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/share/$shareId": {
      id: "/share/$shareId"
      path: "/share/$shareId"
      fullPath: "/share/$shareId"
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/devices": {
      id: "/settings/devices"
      path: "/settings/devices"
      fullPath: "/settings/devices"
      preLoaderRoute: typeof SettingsDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/experts/$expertId": {
      id: "/experts/$expertId"
      path: "/$expertId"
      fullPath: "/experts/$expertId"
      preLoaderRoute: typeof ExpertsExpertIdRouteImport
      parentRoute: typeof ExpertsRoute
    }
    "/workspace/$workspaceId/": {
      id: "/workspace/$workspaceId/"
      path: "/"
      fullPath: "/workspace/$workspaceId/"
      preLoaderRoute: typeof WorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
    "/workspace/$workspaceId/trace": {
      id: "/workspace/$workspaceId/trace"
      path: "/trace"
      fullPath: "/workspace/$workspaceId/trace"
      preLoaderRoute: typeof WorkspaceWorkspaceIdTraceRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
    "/workspace/$workspaceId/monitoring": {
      id: "/workspace/$workspaceId/monitoring"
      path: "/monitoring"
      fullPath: "/workspace/$workspaceId/monitoring"
      preLoaderRoute: typeof WorkspaceWorkspaceIdMonitoringRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
    "/settings/security/sandbox": {
      id: "/settings/security/sandbox"
      path: "/settings/security/sandbox"
      fullPath: "/settings/security/sandbox"
      preLoaderRoute: typeof SettingsSecuritySandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/workspace/$workspaceId/task/$taskId": {
      id: "/workspace/$workspaceId/task/$taskId"
      path: "/task/$taskId"
      fullPath: "/workspace/$workspaceId/task/$taskId"
      preLoaderRoute: typeof WorkspaceWorkspaceIdTaskTaskIdRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
  }
}

interface ExpertsRouteChildren {
  ExpertsExpertIdRoute: typeof ExpertsExpertIdRoute
}

const ExpertsRouteChildren: ExpertsRouteChildren = {
  ExpertsExpertIdRoute: ExpertsExpertIdRoute,
}

const ExpertsRouteWithChildren =
  ExpertsRoute._addFileChildren(ExpertsRouteChildren)

interface WorkspaceWorkspaceIdRouteChildren {
  WorkspaceWorkspaceIdMonitoringRoute: typeof WorkspaceWorkspaceIdMonitoringRoute
  WorkspaceWorkspaceIdTraceRoute: typeof WorkspaceWorkspaceIdTraceRoute
  WorkspaceWorkspaceIdIndexRoute: typeof WorkspaceWorkspaceIdIndexRoute
  WorkspaceWorkspaceIdTaskTaskIdRoute: typeof WorkspaceWorkspaceIdTaskTaskIdRoute
}

const WorkspaceWorkspaceIdRouteChildren: WorkspaceWorkspaceIdRouteChildren = {
  WorkspaceWorkspaceIdMonitoringRoute: WorkspaceWorkspaceIdMonitoringRoute,
  WorkspaceWorkspaceIdTraceRoute: WorkspaceWorkspaceIdTraceRoute,
  WorkspaceWorkspaceIdIndexRoute: WorkspaceWorkspaceIdIndexRoute,
  WorkspaceWorkspaceIdTaskTaskIdRoute: WorkspaceWorkspaceIdTaskTaskIdRoute,
}

const WorkspaceWorkspaceIdRouteWithChildren =
  WorkspaceWorkspaceIdRoute._addFileChildren(WorkspaceWorkspaceIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  AutomationRoute: AutomationRoute,
  ExpertsRoute: ExpertsRouteWithChildren,
  FilesRoute: FilesRoute,
  LoginRoute: LoginRoute,
  MemoryRoute: MemoryRoute,
  NoTenantRoute: NoTenantRoute,
  RegularTasksRoute: RegularTasksRoute,
  SelectTenantRoute: SelectTenantRoute,
  UserSettingsRoute: UserSettingsRoute,
  WorkspacesRoute: WorkspacesRoute,
  SettingsDevicesRoute: SettingsDevicesRoute,
  ShareShareIdRoute: ShareShareIdRoute,
  SharedReportTokenRoute: SharedReportTokenRoute,
  TempTaskIdRoute: TempTaskIdRoute,
  WorkspaceWorkspaceIdRoute: WorkspaceWorkspaceIdRouteWithChildren,
  SettingsSecuritySandboxRoute: SettingsSecuritySandboxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
