/**
 * Icon name → component resolver.
 * Maps the kebab-case icon strings used by sidebar/tabs to lucide-react components.
 * Only imports icons that are actually used as nav items.
 */
import {
  Home,
  LayoutDashboard,
  ShieldAlert,
  Activity,
  Briefcase,
  Lightbulb,
  Ship,
  FolderOpen,
  Compass,
  Shield,
  Sparkles,
  Hourglass,
  FileSignature,
  PenTool,
  RefreshCw,
  DollarSign,
  Calculator,
  CreditCard,
  GitBranch,
  Network,
  ShieldCheck,
  PieChart,
  LineChart,
  Settings,
  FileText,
  Scale,
  BookOpen,
  Beaker,
  Building2,
  Bookmark,
  Users,
  Factory,
  Store,
  ScrollText,
  Brain,
  MailCheck,
  BarChart3,
  TicketCheck,
  Globe,
  Search,
  FilePenLine,
  Lock,
  Bot,
  Radar,
  Microscope,
  FlaskConical,
  Stethoscope,
  PackageSearch,
  TrendingUp,
  Target,
  Palette,
  Megaphone,
  Flame,
  Share2,
  Send,
  FileSearch,
  Landmark,
  LayoutTemplate,
  ClipboardList,
  FileOutput,
  DoorOpen,
  MonitorSmartphone,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  home: Home,
  "layout-dashboard": LayoutDashboard,
  "shield-alert": ShieldAlert,
  activity: Activity,
  briefcase: Briefcase,
  lightbulb: Lightbulb,
  ship: Ship,
  "folder-open": FolderOpen,
  compass: Compass,
  shield: Shield,
  sparkles: Sparkles,
  hourglass: Hourglass,
  "file-signature": FileSignature,
  "pen-tool": PenTool,
  "refresh-cw": RefreshCw,
  "dollar-sign": DollarSign,
  calculator: Calculator,
  "credit-card": CreditCard,
  "git-branch": GitBranch,
  network: Network,
  "shield-check": ShieldCheck,
  "pie-chart": PieChart,
  "line-chart": LineChart,
  settings: Settings,
  "file-text": FileText,
  scale: Scale,
  "book-open": BookOpen,
  beaker: Beaker,
  "building-2": Building2,
  bookmark: Bookmark,
  users: Users,
  factory: Factory,
  store: Store,
  "scroll-text": ScrollText,
  brain: Brain,
  "mail-check": MailCheck,
  "bar-chart-3": BarChart3,
  "ticket-check": TicketCheck,
  globe: Globe,
  search: Search,
  "file-pen-line": FilePenLine,
  lock: Lock,
  bot: Bot,
  radar: Radar,
  microscope: Microscope,
  "flask-conical": FlaskConical,
  stethoscope: Stethoscope,
  "package-search": PackageSearch,
  "trending-up": TrendingUp,
  target: Target,
  palette: Palette,
  megaphone: Megaphone,
  flame: Flame,
  "share-2": Share2,
  send: Send,
  // A7 孤兒頁入口(v1.5):證據/保全/進程模板/服務報告/證據產出/客戶門戶
  "file-search": FileSearch,
  landmark: Landmark,
  "layout-template": LayoutTemplate,
  "clipboard-list": ClipboardList,
  "file-output": FileOutput,
  "door-open": DoorOpen,
  // 桌面能力中继方案 §9.4:用户菜单「我的设备」/settings/devices
  "monitor-smartphone": MonitorSmartphone,
};

/** Resolve an icon name string to a lucide-react component, with fallback. */
export function resolveIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? LayoutDashboard;
}
