#!/usr/bin/env node
/**
 * assemble.mjs — 核心+业务域合树构建(拆库方案 §4.3 组装式构建)。
 *
 * 用法:
 *   node scripts/assemble.mjs [--mode server|production|...]   # 其余参数透传 vite build
 *   npm run build:full            # = assemble --mode production
 *   npm run build:server:full     # = assemble --mode server
 *
 * 流程(FAST FAIL):
 *   1. 清空并重建 .assemble/ = 整仓拷贝(排除 node_modules/dist/.git/.assemble)
 *      —— biz/ 一并拷入(manifest 需要)。
 *   2. 每个 biz/<domain>/ 合树(F7a 防漂移守卫:对核心源树判重,见 guardNoOverwrite):
 *        biz/<d>/routes/*      → .assemble/src/routes/
 *        biz/<d>/components/<c> → .assemble/src/components/<c>
 *        biz/<d>/lib/*          → .assemble/src/lib/
 *   3. 重写 .assemble/src/lib/biz-registry.ts ← 聚合各 manifest 的 sidebarGroups。
 *   4. symlink node_modules → 仓库根(依赖不重复安装)。
 *   5. 在 .assemble/ 内执行 `npx vite build <透传参数>`。
 *
 * 核心/开源构建不经本脚本(npm run build / build:server 直接 vite build,
 * biz/ 不在场 = 代码不存在)。
 */
import { spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const APP = process.cwd();
const OUT = join(APP, ".assemble");
// biz 根:默认单仓形态(APP/biz);拆库后(拆库方案 §4.2)闭源业务域在独立仓,
// 经 DAVY_BIZ_ROOT 指向该仓的 biz/ 目录(相对路径按 APP 解析),如:
//   DAVY_BIZ_ROOT=../../davy-cloud/biz npm run build:server:full
const BIZ = process.env.DAVY_BIZ_ROOT ? resolve(process.env.DAVY_BIZ_ROOT) : join(APP, "biz");

const EXCLUDE = new Set(["node_modules", "dist", ".git", ".assemble", ".enterprise"]);

function copyApp() {
  rmSync(OUT, { recursive: true, force: true });
  mkdirSync(OUT, { recursive: true });
  for (const entry of readdirSync(APP, { withFileTypes: true })) {
    if (EXCLUDE.has(entry.name)) continue;
    cpSync(join(APP, entry.name), join(OUT, entry.name), {
      recursive: true,
      filter: (src) => !EXCLUDE.has(src.split("/").pop() ?? ""),
    });
  }
}

function listDomains() {
  if (!existsSync(BIZ)) return [];
  return readdirSync(BIZ, { withFileTypes: true })
    .filter((d) => d.isDirectory() && existsSync(join(BIZ, d.name, "manifest.ts")))
    .map((d) => d.name);
}

// F7a(拆库方案 §5.2 组装防漂移):biz 只能"新增"文件,禁止覆盖核心树。
// 对核心源树(APP 下同路径)判重 + 跨 biz 域命名空间互斥;冲突 = 漂移,FAST FAIL。
// 唯一豁免:src/lib/biz-registry.ts 由 writeRegistry() 显式重写(组装接缝)。
const claimed = new Set();
function guardNoOverwrite(relPath, domain) {
  if (existsSync(join(APP, relPath))) {
    console.error(
      `[assemble] FATAL (F7a): biz/${domain} 试图覆盖核心文件 ${relPath} —— biz 只能新增文件,禁止改动核心树。`,
    );
    process.exit(1);
  }
  if (claimed.has(relPath)) {
    console.error(`[assemble] FATAL (F7a): biz/${domain} 与更早的 biz 域路径冲突 ${relPath} —— 各域命名空间必须互斥。`);
    process.exit(1);
  }
  claimed.add(relPath);
}

// lib 递归合树:允许 biz 向核心已有目录「新增」文件(部分目录共享,如
// src/lib/api/ —— api/index.ts 留核心,biz/normflow 补回 normflow.ts)。
// F7a 判重下沉到文件级:核心树同路径文件存在 / 跨域重复 = 漂移,FAST FAIL。
function mergeLibDeep(srcDir, relDir, domain) {
  for (const f of readdirSync(srcDir, { withFileTypes: true })) {
    const relPath = `${relDir}/${f.name}`;
    if (f.isDirectory()) {
      mergeLibDeep(join(srcDir, f.name), relPath, domain);
    } else {
      guardNoOverwrite(relPath, domain);
      mkdirSync(join(OUT, relDir), { recursive: true });
      cpSync(join(srcDir, f.name), join(OUT, relPath));
    }
  }
}

function mergeDomain(domain) {
  const root = join(BIZ, domain);
  const pairs = [
    [join(root, "routes"), "src/routes"],
    [join(root, "hooks"), "src/hooks"],
  ];
  for (const [src, rel] of pairs) {
    if (!existsSync(src)) continue;
    const dest = join(OUT, rel);
    mkdirSync(dest, { recursive: true });
    for (const f of readdirSync(src)) {
      guardNoOverwrite(`${rel}/${f}`, domain);
      cpSync(join(src, f), join(dest, f), { recursive: true });
    }
  }
  const libRoot = join(root, "lib");
  if (existsSync(libRoot)) mergeLibDeep(libRoot, "src/lib", domain);
  const compRoot = join(root, "components");
  if (existsSync(compRoot)) {
    for (const c of readdirSync(compRoot, { withFileTypes: true })) {
      guardNoOverwrite(`src/components/${c.name}`, domain);
      cpSync(join(compRoot, c.name), join(OUT, "src", "components", c.name), { recursive: true });
    }
  }
}

const REGISTRY_TEMPLATE = `// AUTO-GENERATED by scripts/assemble.mjs — 勿手改(核心树中为空表)。
// 核心构建:业务域不在场,恒为空表;assemble 时由 writeRegistry 重写注入。
import type { ComponentType } from "react";
import type { SidebarGroup } from "./sidebar-config";

// ── 工作区专属 ChatView 注册(任务路由按 workspaceType/name 分发)──
export interface WorkspaceChatEntry {
  /** 命中判断:workspaceType/name 二元组 */
  match: (ctx: { workspaceType?: string | null; name?: string | null }) => boolean;
  /** 命中后渲染的任务页 ChatView 组件 */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  component: ComponentType<any>;
  /** 命中时页面上下文 Dock 的 module 字段(不设则走默认 workspace-task) */
  agentModule?: string;
  /** task.title 为空时摘要文案的 i18n key(不设则回退 workspace.name) */
  agentSummaryKey?: string;
}

// ── 工作区空状态注册(chat-view 空消息时的模块化引导界面)──
export interface WorkspaceEmptyStateConfig {
  /** Icon name from lucide-react (resolved at render time) */
  icon: string;
  title: string;
  description: string;
  primaryAction: string;
  primaryIsUpload?: boolean;
  secondaryAction?: string;
  secondaryActionPrompt?: string;
}
export interface WorkspaceEmptyStateEntry {
  /** workspaceType === prefix,或 workspace.name 以 prefix- 开头时命中 */
  prefix: string;
  config: WorkspaceEmptyStateConfig;
}

// ── 工作区空状态组件注册(组件型;chat-view 空消息引导界面的整组件形态)──
export interface WorkspaceEmptyComponentEntry {
  /** 命中判断:workspaceType/name 二元组 */
  match: (ctx: { workspaceType?: string | null; name?: string | null }) => boolean;
  /** 命中后渲染的空状态组件(onInsert 向输入框注入快捷指令) */
  component: ComponentType<{ onInsert: (text: string) => void }>;
}

// ── Agent fleet 状态下沉注册(monitoring-ws 的 WS 消息 → 域内 store)──
export interface AgentStatusSinkEntry {
  /** WS 消息 type(如 "market_agent_status";契约 { data: { expert_id, status, last_action? } }) */
  messageType: string;
  /** 命中时调用域内 store 的 setAgentStatus(expertId, status, lastAction?) */
  setAgentStatus: (expertId: string, status: string, lastAction?: string) => void;
}

// ── sidebar 分组上下文行注册(产品/品牌全局切换等;按 group.key 挂载)──
export interface SidebarContextSelectEntry {
  /** 挂载目标 sidebar 分组 key */
  groupKey: string;
  /** 行标签:静态串或取值函数(支持 i18n 动态解析) */
  label: string | (() => string);
  /** 上下文选择组件 */
  component: ComponentType;
}

// ── 身份切换重置钩子注册(reset-stores 逐个 try/catch 调用)──
export interface IdentityResetHookEntry {
  /** 重置域内 tenant-scoped store(如 social brand 上下文);异常由调用方吞掉 */
  reset: () => void;
}

// ── sidebar 徽标计数注册(取数/轮询逻辑在域内 hook;core 侧只做合并)──
export interface SidebarCountHookEntry {
  /** 返回本域计数(key = sidebar item countKey;如 activeCases/pendingLeads) */
  useCounts: () => Record<string, number>;
}

// ── 根布局浮动 Dock 注册(如 FirmAgentDock;按模块键命中,__root 统一 lazy 化)──
export interface RootDockEntry {
  /** 模块键命中判断(moduleKey = routeToModuleKey(path)) */
  match: (moduleKey: string) => boolean;
  /** 动态加载 Dock 组件(保持 chunk 分包;返回 { default: ComponentType }) */
  load: () => Promise<{ default: ComponentType }>;
}

__IMPORTS__

export const BIZ_SIDEBAR_GROUPS: SidebarGroup[] = [
__SIDEBAR_SPREADS__
];

export const BIZ_TASK_CHAT_VIEWS: WorkspaceChatEntry[] = [
__CHAT_SPREADS__
];

export const BIZ_WORKSPACE_EMPTY_STATES: WorkspaceEmptyStateEntry[] = [
__EMPTY_SPREADS__
];

export const BIZ_WORKSPACE_EMPTY_COMPONENTS: WorkspaceEmptyComponentEntry[] = [
__EMPTYCOMP_SPREADS__
];

export const BIZ_AGENT_STATUS_SINKS: AgentStatusSinkEntry[] = [
__SINK_SPREADS__
];

export const BIZ_SIDEBAR_CONTEXT_SELECTS: SidebarContextSelectEntry[] = [
__CTXSEL_SPREADS__
];

export const BIZ_IDENTITY_RESET_HOOKS: IdentityResetHookEntry[] = [
__RESET_SPREADS__
];

export const BIZ_SIDEBAR_COUNT_HOOKS: SidebarCountHookEntry[] = [
__COUNT_SPREADS__
];

export const BIZ_ROOT_DOCKS: RootDockEntry[] = [
__DOCK_SPREADS__
];
`;

function writeRegistry(domains) {
  const imports = [];
  const sidebarSpreads = [];
  const chatSpreads = [];
  const emptySpreads = [];
  const emptyCompSpreads = [];
  const sinkSpreads = [];
  const ctxSelSpreads = [];
  const resetSpreads = [];
  const countSpreads = [];
  const dockSpreads = [];
  for (const d of domains) {
    const src = readFileSync(join(BIZ, d, "manifest.ts"), "utf8");
    // 域名可含连字符(deep-research 等),别名须是合法 JS 标识符(路径保持原样)
    const id = d.replace(/[^A-Za-z0-9_]/g, "_");
    imports.push(`import { sidebarGroups as _${id} } from "../../biz/${d}/manifest";`);
    sidebarSpreads.push(`  ..._${id},`);
    if (/export\s+const\s+taskChatViews/.test(src)) {
      imports.push(`import { taskChatViews as _tcv_${id} } from "../../biz/${d}/manifest";`);
      chatSpreads.push(`  ..._tcv_${id},`);
    }
    if (/export\s+const\s+workspaceEmptyStates/.test(src)) {
      imports.push(`import { workspaceEmptyStates as _wes_${id} } from "../../biz/${d}/manifest";`);
      emptySpreads.push(`  ..._wes_${id},`);
    }
    if (/export\s+const\s+workspaceEmptyComponents/.test(src)) {
      imports.push(`import { workspaceEmptyComponents as _wec_${id} } from "../../biz/${d}/manifest";`);
      emptyCompSpreads.push(`  ..._wec_${id},`);
    }
    if (/export\s+const\s+agentStatusSinks/.test(src)) {
      imports.push(`import { agentStatusSinks as _sink_${id} } from "../../biz/${d}/manifest";`);
      sinkSpreads.push(`  ..._sink_${id},`);
    }
    if (/export\s+const\s+sidebarContextSelects/.test(src)) {
      imports.push(`import { sidebarContextSelects as _ctxs_${id} } from "../../biz/${d}/manifest";`);
      ctxSelSpreads.push(`  ..._ctxs_${id},`);
    }
    if (/export\s+const\s+identityResetHooks/.test(src)) {
      imports.push(`import { identityResetHooks as _irh_${id} } from "../../biz/${d}/manifest";`);
      resetSpreads.push(`  ..._irh_${id},`);
    }
    if (/export\s+const\s+sidebarCountHooks/.test(src)) {
      imports.push(`import { sidebarCountHooks as _sch_${id} } from "../../biz/${d}/manifest";`);
      countSpreads.push(`  ..._sch_${id},`);
    }
    if (/export\s+const\s+rootDocks/.test(src)) {
      imports.push(`import { rootDocks as _dock_${id} } from "../../biz/${d}/manifest";`);
      dockSpreads.push(`  ..._dock_${id},`);
    }
  }
  const content = REGISTRY_TEMPLATE.replace("__IMPORTS__", imports.join("\n"))
    .replace("__SIDEBAR_SPREADS__", sidebarSpreads.join("\n"))
    .replace("__CHAT_SPREADS__", chatSpreads.join("\n"))
    .replace("__EMPTY_SPREADS__", emptySpreads.join("\n"))
    .replace("__EMPTYCOMP_SPREADS__", emptyCompSpreads.join("\n"))
    .replace("__SINK_SPREADS__", sinkSpreads.join("\n"))
    .replace("__CTXSEL_SPREADS__", ctxSelSpreads.join("\n"))
    .replace("__RESET_SPREADS__", resetSpreads.join("\n"))
    .replace("__COUNT_SPREADS__", countSpreads.join("\n"))
    .replace("__DOCK_SPREADS__", dockSpreads.join("\n"));
  writeFileSync(join(OUT, "src", "lib", "biz-registry.ts"), content);
}

function main() {
  const domains = listDomains();
  if (domains.length === 0) {
    console.error("[assemble] FATAL: 未发现任何业务域(biz/<domain>/manifest.ts)。");
    console.error("[assemble]   单仓形态: app 根下应含 biz/;");
    console.error("[assemble]   拆库跨仓形态: 设置 DAVY_BIZ_ROOT 指向闭源仓 biz/ 目录(见 davy-cloud README);");
    console.error("[assemble]   仅核心构建请用 npm run build / build:server(不经本脚本)。");
    process.exit(1);
  }
  console.log(`[assemble] domains: ${domains.join(", ")}`);
  copyApp();
  // 跨仓形态(DAVY_BIZ_ROOT):APP 拷贝不含 biz → 把各域 manifest 落位
  // .assemble/biz/<d>/,供 writeRegistry 生成的相对导入(../../biz/<d>/manifest)
  // 解析。manifest 仅 import "../../src/..." 合树路径(§11.3),故单文件自洽;
  // 单仓形态下 copyApp 已整树拷入,此处为幂等重写。
  for (const d of domains) {
    mkdirSync(join(OUT, "biz", d), { recursive: true });
    cpSync(join(BIZ, d, "manifest.ts"), join(OUT, "biz", d, "manifest.ts"));
  }
  for (const d of domains) mergeDomain(d);
  writeRegistry(domains);
  symlinkSync(join(APP, "node_modules"), join(OUT, "node_modules"), "dir");

  const passThrough = process.argv.slice(2);
  const res = spawnSync("npx", ["vite", "build", ...passThrough], {
    cwd: OUT,
    stdio: "inherit",
  });
  if (res.status !== 0) {
    console.error(`[assemble] vite build failed (exit ${res.status})`);
    process.exit(res.status ?? 1);
  }
  console.log(`[assemble] done → ${join(OUT, "dist")}`);
}

main();
